import {readFile} from 'node:fs/promises';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {NextRequest} from 'next/server';
const {getContext,adminFetch}=vi.hoisted(()=>({getContext:vi.fn(),adminFetch:vi.fn()}));
vi.mock('../lib/dpt-admin-api',()=>({getDptAdminApiContext:getContext,dptAdminSupabaseFetch:adminFetch}));
import {GET,POST} from '../app/api/admin/tournaments/[id]/relationships/route';
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
const values={advancing_to_flight_tournaments:true,allow_search_registration:true,chip_carryover:'highest',flights:[],qualifiers:[],toc_all_types:true,toc_type_ids:[1],toc_tournament_ids:[2]};
describe('tournament relationship administration',()=>{
 beforeEach(()=>{vi.clearAllMocks();getContext.mockResolvedValue({accessToken:'x'});});
 it('fails closed',async()=>{getContext.mockResolvedValue(null);expect((await GET(new NextRequest('http://x/api/admin/tournaments/1/relationships'))).status).toBe(401);expect(adminFetch).not.toHaveBeenCalled();});
 it('rejects unknown top-level and nested fields',async()=>{expect((await POST(new NextRequest('http://x/api/admin/tournaments/1/relationships',{method:'POST',body:JSON.stringify({...values,injected:true})}))).status).toBe(400);const badFlight={id:null,name:'A',starts_at:'',ends_at:'',registration_starts_at:'',registration_ends_at:'',minimum_buyin:0,tournament_fee_percent:0,initial_chips_count:0,injected:true};expect((await POST(new NextRequest('http://x/api/admin/tournaments/1/relationships',{method:'POST',body:JSON.stringify({...values,flights:[badFlight]})}))).status).toBe(400);});
 it('aggregates current relations and named options',async()=>{adminFetch.mockResolvedValueOnce(json([{id:9,advancing_to_flight_tournaments:true,allow_search_registration:true,chip_carryover:'sum',toc_all_types:false}])).mockResolvedValueOnce(json([{id:10,name:'Flight A'}])).mockResolvedValueOnce(json([{qualifier_tournament_id:11,qualifier_prize:'Seat'}])).mockResolvedValueOnce(json([{id:4,name:'Flight',code:'flight'}])).mockResolvedValueOnce(json([{id:11,name:'Main',tournament_type_id:1}])).mockResolvedValueOnce(json([{tournament_type_id:1}])).mockResolvedValueOnce(json([{qualified_tournament_id:11}]));const result=await GET(new NextRequest('http://x/api/admin/tournaments/9/relationships'));const body=await result.json();expect(result.status).toBe(200);expect(body.current.flights).toHaveLength(1);expect(body.current.qualifiers[0]).toEqual({tournament_id:11,qualifier_prize:'Seat'});expect(body.current.toc_type_ids).toEqual([1]);expect(body.options.tournaments[0].name).toBe('Main');});
 it('sends only the guarded relationship RPC',async()=>{adminFetch.mockResolvedValue(json({ok:true}));const response=await POST(new NextRequest('http://x/api/admin/tournaments/9/relationships',{method:'POST',body:JSON.stringify(values)}));expect(response.status).toBe(200);expect(adminFetch).toHaveBeenCalledWith(expect.anything(),'/rest/v1/rpc/dpt_admin_save_tournament_relationships',expect.objectContaining({body:JSON.stringify({p_main_id:9,p_values:values})}));});
 it('makes runtime child flights immutable and relationship copies standalone',async()=>{const migration=await readFile(new URL('../../../supabase/migrations/20260719200000_admin_tournament_relationships.sql',import.meta.url),'utf8');expect(migration).toContain('Flight with entries or advancements is read-only');expect(migration).toContain('Flight with entries or advancements cannot be removed');expect(migration).toContain("name||' Copy'");expect(migration).toContain('false,false,multi_day');expect(migration).not.toContain('insert into public.tournament_qualifiers(tournament_id,qualifier_tournament_id,qualifier_prize) select new_id');});
 it('matches production relationship labels and read-only existing flights',async()=>{const ui=await readFile(new URL('../components/tournament-relationships.tsx',import.meta.url),'utf8');for(const label of ['Flight Tournaments?','Direct Registration to Main Tournament','Chip Accumulator','Add Flight Tournament','Qualifier Tournament','Qualifier Prize','Tournament of Champions Qualifiers','All Tournament Types','Specific Tournaments','Save Relationships'])expect(ui).toContain(label);expect(ui).toContain('readOnly={Boolean(flight.id)}');expect(ui).toContain('existing flight — read-only');expect(ui).toContain('setCurrent({...p.record,flights})');});
});
