import {readFile} from 'node:fs/promises';
import {beforeEach,describe,expect,it,vi} from 'vitest';
import {NextRequest} from 'next/server';
const {getContext,adminFetch}=vi.hoisted(()=>({getContext:vi.fn(),adminFetch:vi.fn()}));
vi.mock('../lib/dpt-admin-api',()=>({getDptAdminApiContext:getContext,dptAdminSupabaseFetch:adminFetch}));
import {GET,POST} from '../app/api/admin/notifications/[id]/route';
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});
const campaign='11111111-1111-4111-8111-111111111111',delivery='22222222-2222-4222-8222-222222222222',lease='33333333-3333-4333-8333-333333333333',origin='http://x';
const post=(body:unknown)=>new NextRequest(`${origin}/api/admin/notifications/${campaign}`,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)});
describe('simulated notification delivery queue',()=>{
 beforeEach(()=>{vi.clearAllMocks();getContext.mockResolvedValue({accessToken:'x'});});
 it('fails closed for campaign history and processing',async()=>{getContext.mockResolvedValue(null);expect((await GET(new NextRequest(`${origin}/api/admin/notifications/${campaign}`),{params:{id:campaign}})).status).toBe(401);expect((await POST(post({action:'process'}),{params:{id:campaign}})).status).toBe(401);expect(adminFetch).not.toHaveBeenCalled();});
 it('rejects cross-origin, live mode, providers, destinations and batch overrides',async()=>{expect((await POST(new NextRequest(`${origin}/api/admin/notifications/${campaign}`,{method:'POST',headers:{origin:'https://evil.example','content-type':'application/json'},body:JSON.stringify({action:'process'})}),{params:{id:campaign}})).status).toBe(403);for(const body of [{action:'process',mode:'live'},{action:'process',provider:'sns'},{action:'process',email:'x@example.com'},{action:'process',limit:100}])expect((await POST(post(body),{params:{id:campaign}})).status).toBe(400);expect(adminFetch).not.toHaveBeenCalled();});
 it('loads privacy-safe campaign history through one guarded RPC',async()=>{adminFetch.mockResolvedValue(json({campaign:{id:campaign},deliveries:[],attempts:[]}));const response=await GET(new NextRequest(`${origin}/api/admin/notifications/${campaign}?offset=10`),{params:{id:campaign}});expect(response.status).toBe(200);expect(adminFetch).toHaveBeenCalledWith(expect.anything(),'/rest/v1/rpc/dpt_admin_notification_campaign_detail',expect.objectContaining({body:JSON.stringify({p_campaign_id:campaign,p_offset:10,p_limit:100})}));});
 it('claims only the fixed batch and finalizes with deterministic simulator output',async()=>{adminFetch.mockResolvedValueOnce(json({mode:'simulated',deliveries:[{id:delivery,channel:'email',lease_token:lease}]})).mockResolvedValueOnce(json({id:delivery,status:'sent',simulated:true}));const response=await POST(post({action:'process'}),{params:{id:campaign}});const body=await response.json();expect(response.status).toBe(200);expect(body.simulation).toBe(true);expect(body.processed).toBe(1);expect(adminFetch.mock.calls[0][2].body).toBe(JSON.stringify({p_campaign_id:campaign,p_limit:25}));const finalize=JSON.parse(String(adminFetch.mock.calls[1][2].body));expect(finalize.p_provider_message_id).toMatch(/^sim-email-/);expect(finalize.p_outcome).toBe('sent');});
 it('allows only exact cancel and retry payloads',async()=>{adminFetch.mockImplementation(()=>Promise.resolve(json({id:campaign})));expect((await POST(post({action:'cancel'}),{params:{id:campaign}})).status).toBe(200);expect((await POST(post({action:'retry',delivery_id:delivery}),{params:{id:campaign}})).status).toBe(200);expect((await POST(post({action:'retry',delivery_id:delivery,attempts:0}),{params:{id:campaign}})).status).toBe(400);});
 it('implements all targeting dimensions, rate limits, leases and immutable retries in SQL',async()=>{const sql=await readFile(new URL('../../../supabase/migrations/20260719230000_simulated_notification_delivery_queue.sql',import.meta.url),'utf8');for(const text of ["target->'season_ids'","target->'event_ids'","target->'league_ids'","30-sent_count","10-sent_count",'for update skip locked',"interval '5 minutes'",'attempts+1','max_attempts=least(10','where id=p_delivery_id returning','external_delivery_mode text not null default \'simulated\''])expect(sql).toContain(text);expect(sql).not.toContain('attempts=0');expect(sql).not.toContain("external_delivery_mode = 'live'");});
 it('exposes simulation history without raw destinations',async()=>{const ui=await readFile(new URL('../components/notification-campaign-detail.tsx',import.meta.url),'utf8'),manager=await readFile(new URL('../components/notifications-manager.tsx',import.meta.url),'utf8');for(const label of ['STAGING SIMULATION','Process next 25','Suppression breakdown','immutable attempt history','Sent (simulated)','Retry'])expect(ui).toContain(label);for(const label of ['Purpose','Seasons','Events','Leagues','Create simulated queue','Campaign history'])expect(manager).toContain(label);expect(ui).not.toContain('email_address');expect(ui).not.toContain('phone_number');});
});
