import { NextRequest, NextResponse } from 'next/server';
import { dptAdminSupabaseFetch, getDptAdminApiContext } from '../../../../lib/dpt-admin-api';
export const dynamic='force-dynamic';
const fields=['first_name','last_name','nick_name','email','mobile','country_code','alias','avatar_url','address_line1','address_line2','city','state','postal_code','facebook_url','twitter_url','instagram_url','registration_exception','registration_exception_reason','email_enabled','sms_enabled','tournament_updates','marketing_enabled'];
const bools=new Set(['registration_exception','email_enabled','sms_enabled','tournament_updates','marketing_enabled']);
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const exact=(value:Record<string,unknown>,keys:string[])=>Object.keys(value).every((key)=>keys.includes(key));
const csv=(value:unknown)=>`"${String(value??'').replaceAll('"','""')}"`;
export async function GET(request:NextRequest){
 const context=await getDptAdminApiContext();if(!context)return NextResponse.json({error:'Unauthorized'},{status:401});const q=request.nextUrl.searchParams;
 const detail=q.get('id');const select='id,legacy_user_id,first_name,last_name,nick_name,email,mobile,country_code,alias,avatar_url,status,created_at,updated_at,address_line1,address_line2,city,state,postal_code,facebook_url,twitter_url,instagram_url,registration_exception,registration_exception_reason,merged_into,profile_roles(role),profile_notification_preferences(email_enabled,sms_enabled,tournament_updates,marketing_enabled)';
 if(detail){if(!uuid.test(detail))return NextResponse.json({error:'Invalid player ID'},{status:400});const response=await dptAdminSupabaseFetch(context,`/rest/v1/profiles?select=${encodeURIComponent(select)}&id=eq.${detail}&limit=1`);if(!response.ok)return NextResponse.json({error:'Player unavailable'},{status:502});const rows=await response.json() as any[];if(!rows[0])return NextResponse.json({error:'Player not found'},{status:404});return NextResponse.json({record:rows[0]});}
 const page=Math.max(1,Number(q.get('page')||1));const size=[10,25,50,100,5000].includes(Number(q.get('size')))?Number(q.get('size')):10;const sort=['created_at','first_name','last_name','nick_name','email','mobile'].includes(q.get('sort')||'')?q.get('sort')!:'created_at';const direction=q.get('dir')==='asc'?'asc':'desc';const filters=['deleted_at=is.null','merged_into=is.null',`order=${sort}.${direction}`,`limit=${size}`,`offset=${(page-1)*size}`];
 if(q.get('status')==='archived')filters.splice(0,2,'status=eq.archived');else filters.push('status=eq.active');if(q.get('search')){const term=encodeURIComponent(q.get('search')!.trim());filters.push(`or=(first_name.ilike.*${term}*,last_name.ilike.*${term}*,nick_name.ilike.*${term}*,email.ilike.*${term}*,mobile.ilike.*${term}*)`);}
 const response=await dptAdminSupabaseFetch(context,`/rest/v1/profiles?select=${encodeURIComponent(select)}&${filters.join('&')}`,{headers:{Prefer:'count=exact'}});if(!response.ok)return NextResponse.json({error:'Player list unavailable'},{status:502});const records=await response.json() as any[];
 if(q.get('format')==='csv'){const lines=[['#','First Name','Last Name','Nick Name','Email','Mobile','Roles','Created Date'].map(csv).join(',')];for(const row of records)lines.push([row.legacy_user_id||row.id,row.first_name,row.last_name,row.nick_name,row.email,row.mobile,(row.profile_roles||[]).map((role:any)=>role.role).join('|'),row.created_at].map(csv).join(','));return new NextResponse(lines.join('\n'),{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':'attachment; filename="dpt-players.csv"'}});}
 return NextResponse.json({records,total:Number(response.headers.get('content-range')?.split('/')[1]||0)});
}
export async function POST(request:NextRequest){
 const context=await getDptAdminApiContext();if(!context)return NextResponse.json({error:'Unauthorized'},{status:401});let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>;}catch{return NextResponse.json({error:'Invalid JSON body'},{status:400});}
 if(!body||typeof body.action!=='string')return NextResponse.json({error:'Invalid player action'},{status:400});let rpc:string,payload:Record<string,unknown>;
 if(body.action==='save'){if(!exact(body,['action','id','values'])||!body.values||typeof body.values!=='object'||Array.isArray(body.values)||(body.id!==undefined&&body.id!==null&&(!uuid.test(String(body.id))))||Object.keys(body.values as object).some((key)=>!fields.includes(key)))return NextResponse.json({error:'Invalid player payload'},{status:400});const values=body.values as Record<string,unknown>;if(typeof values.first_name!=='string'||!values.first_name.trim()||typeof values.last_name!=='string'||!values.last_name.trim())return NextResponse.json({error:'First and last name are required'},{status:400});for(const key of bools)if(key in values&&typeof values[key]!=='boolean')return NextResponse.json({error:`Invalid ${key}`},{status:400});rpc='dpt_admin_save_player';payload={p_id:body.id??null,p_values:values};}
 else if(body.action==='archive'&&exact(body,['action','id'])&&uuid.test(String(body.id))){rpc='dpt_admin_archive_player';payload={p_id:body.id};}else return NextResponse.json({error:'Invalid player action'},{status:400});
 const response=await dptAdminSupabaseFetch(context,`/rest/v1/rpc/${rpc}`,{method:'POST',body:JSON.stringify(payload)});if(!response.ok)return NextResponse.json({error:'Player change was rejected',detail:await response.text()},{status:response.status===401||response.status===403?403:409});return NextResponse.json({record:await response.json()},{status:body.action==='save'&&!body.id?201:200});
}
