'use client';
import { useEffect, useState } from 'react';
type Detail = Record<string, any>;
export function NotificationCampaignDetail({ id }: { id: string }) {
 const [detail, setDetail] = useState<Detail | null>(null); const [note, setNote] = useState('');
 const load = async () => { const r = await fetch(`/api/admin/notifications/${id}`, { cache: 'no-store' }); const x = await r.json(); if (r.ok) setDetail(x); else setNote(x.error || 'Campaign unavailable'); };
 useEffect(() => { void load(); }, [id]);
 const act = async (action: 'process' | 'cancel' | 'retry', delivery_id?: string) => { const r = await fetch(`/api/admin/notifications/${id}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action, ...(delivery_id ? { delivery_id } : {}) }) }); const x = await r.json(); setNote(r.ok ? (action === 'process' ? `Simulated ${x.processed} queued delivery(s).` : 'Queue updated.') : x.error || 'Action rejected'); if (r.ok) await load(); };
 if (!detail) return <p>{note || 'Loading simulation history…'}</p>;
 const campaign = detail.campaign || {}; const summary = detail.summary || {}; const suppressions = detail.suppressions || {};
 return <section className="configuration-form"><header><div><h3>{campaign.title}</h3><p><strong>STAGING SIMULATION</strong> — no provider calls are possible.</p></div><div><button type="button" onClick={() => void act('process')}>Process next 25</button>{!['cancelled','completed','completed_with_failures'].includes(campaign.status) && <button type="button" onClick={() => void act('cancel')}>Cancel</button>}</div></header><p>{note}</p><div className="configuration-form-grid"><div><strong>Status</strong><br />{campaign.status}</div><div><strong>Queued</strong><br />{summary.queued || 0}</div><div><strong>Sent (simulated)</strong><br />{summary.sent || 0}</div><div><strong>Suppressed</strong><br />{summary.suppressed || 0}</div><div><strong>Failed</strong><br />{summary.failed || 0}</div></div><h4>Suppression breakdown</h4><ul>{Object.entries(suppressions).map(([reason,count]) => <li key={reason}>{reason}: {String(count)}</li>)}</ul><h4>Deliveries and immutable attempt history</h4><table><thead><tr><th>Recipient</th><th>Channel</th><th>Status</th><th>Attempts</th><th>Reason</th><th>Simulation ID</th><th /></tr></thead><tbody>{(detail.deliveries || []).map((d: Detail) => <tr key={d.id}><td>{d.recipient_snapshot?.name||'Unknown profile'}</td><td>{d.channel}</td><td>{d.status}</td><td>{d.attempts}/{d.max_attempts}</td><td>{d.suppression_reason || d.error_code || '—'}</td><td>{d.provider_message_id || '—'}</td><td>{d.status === 'failed' && <button type="button" onClick={() => void act('retry', d.id)}>Retry</button>}</td></tr>)}</tbody></table><h4>Attempts</h4><ul>{(detail.attempts || []).map((a: Detail) => <li key={a.id}>{a.created_at}: {a.outcome} ({a.error_code || a.provider_message_id || 'simulated'})</li>)}</ul></section>;
}
