'use client';
import Link from 'next/link'; import { useEffect, useState } from 'react';
type Row = Record<string, any>; const empty = { venues: [], seasons: [], events: [], leagues: [], tournaments: [], roles: [] };
export function NotificationsManager() {
 const [title,setTitle]=useState(''),[message,setMessage]=useState(''),[purpose,setPurpose]=useState('general'),[email,setEmail]=useState(false),[sms,setSms]=useState(false),[smsBody,setSmsBody]=useState(''),[profileIds,setProfileIds]=useState(''),[target,setTarget]=useState<Row>({venue_ids:[],season_ids:[],event_ids:[],league_ids:[],tournament_ids:[],role_names:[]}),[options,setOptions]=useState<Row>(empty),[campaigns,setCampaigns]=useState<Row[]>([]),[note,setNote]=useState('');
 const load=async()=>{const r=await fetch('/api/admin/notifications',{cache:'no-store'});const x=await r.json();if(r.ok){setCampaigns(x.records||[]);setOptions(x.options||empty)}else setNote(x.error||'Campaigns unavailable')}; useEffect(()=>{void load()},[]);
 const submit=async(dry_run:boolean)=>{const values={title,message_html:message,purpose,email_enabled:email,sms_enabled:sms,sms_body:smsBody,profile_ids:profileIds.split(',').map(x=>x.trim()).filter(Boolean),target,dry_run};const r=await fetch('/api/admin/notifications',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idempotency_key:crypto.randomUUID(),values})});const x=await r.json();if(!r.ok)return setNote(x.error||'Rejected');setNote(dry_run?`Preview: ${x.campaign.recipients} recipients; ${x.campaign.queued||0} would queue and ${x.campaign.suppressed||0} would be suppressed. Nothing persisted.`:`Campaign queued for simulation: ${x.campaign.recipients} recipients. Internal notifications are sent; email/SMS remain in the staging-only simulated queue.`);if(!dry_run)await load()};
 const multi=(label:string,key:string,items:Row[],valueKey='id',labelKey='name')=><label>{label}<select multiple value={target[key]||[]} onChange={e=>setTarget({...target,[key]:[...e.target.selectedOptions].map(o=>valueKey==='id'?Number(o.value):o.value)})}>{items.map(i=><option key={String(i[valueKey])} value={i[valueKey]}>{i[labelKey]}</option>)}</select></label>;
 return <section className="configuration-form"><header><div><h3>Send Notifications — staging simulation queue</h3><p>Email and SMS are never sent externally. Delivery mode is server/database locked to simulated.</p></div></header><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} /></label><label>Message HTML<textarea value={message} onChange={e=>setMessage(e.target.value)} /></label><label>Purpose<select value={purpose} onChange={e=>setPurpose(e.target.value)}><option value="general">General</option><option value="tournament_update">Tournament Update</option><option value="marketing">Marketing</option></select></label><label><input type="checkbox" checked={email} onChange={e=>setEmail(e.target.checked)} /> Email notification — queue simulation</label><label><input type="checkbox" checked={sms} onChange={e=>setSms(e.target.checked)} /> SMS notification — queue simulation</label>{sms&&<label>SMS body<textarea value={smsBody} onChange={e=>setSmsBody(e.target.value)} /></label>}<label>Explicit profile IDs (comma separated)<textarea value={profileIds} onChange={e=>setProfileIds(e.target.value)} /></label>{multi('Venues','venue_ids',options.venues)}{multi('Seasons','season_ids',options.seasons)}{multi('Events','event_ids',options.events)}{multi('Leagues','league_ids',options.leagues)}{multi('Tournaments','tournament_ids',options.tournaments)}{multi('Roles','role_names',options.roles,'name','display_name')}<div><button type="button" onClick={()=>void submit(true)}>Preview eligibility</button><button type="button" onClick={()=>void submit(false)}>Create simulated queue</button></div><p>{note}</p><h3>Campaign history</h3><table><thead><tr><th>Title</th><th>Status</th><th>Created</th><th>Mode</th></tr></thead><tbody>{campaigns.map(c=><tr key={c.id}><td><Link href={`/admin/send-notifications/${c.id}`}>{c.title}</Link></td><td>{c.status}</td><td>{c.created_at}</td><td>{c.external_delivery_mode||'simulated'}</td></tr>)}</tbody></table></section>;
}
