'use client';
import { FormEvent, useEffect, useState } from 'react';
type Row=Record<string,any>;
const blankFlight=()=>({id:null,name:'',starts_at:'',ends_at:'',registration_starts_at:'',registration_ends_at:'',minimum_buyin:0,tournament_fee_percent:0,initial_chips_count:0});
const date=(v:any)=>typeof v==='string'&&v?v.slice(0,16):'';
export function TournamentRelationships({id,onClose}:{id:number;onClose:()=>void}){
 const [current,setCurrent]=useState<Row|null>(null),[options,setOptions]=useState<{types:Row[];tournaments:Row[]}>({types:[],tournaments:[]}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{void (async()=>{const r=await fetch(`/api/admin/tournaments/${id}/relationships`,{cache:'no-store'}),p=await r.json();if(!r.ok){setMessage(p.error||'Unable to load relationships');return;} const flights=p.current.flights.map((f:Row)=>({...blankFlight(),...f,starts_at:date(f.starts_at),ends_at:date(f.ends_at),registration_starts_at:date(f.registration_starts_at),registration_ends_at:date(f.registration_ends_at)})); setCurrent({...p.current,flights});setOptions(p.options);})()},[id]);
 if(!current)return <section className="configuration-form"><p>{message||'Loading tournament relationships…'}</p><button onClick={onClose}>Close</button></section>;
 const set=(key:string,value:any)=>setCurrent(x=>x?{...x,[key]:value}:x);
 const updateFlight=(i:number,key:string,value:any)=>set('flights',current.flights.map((f:Row,n:number)=>n===i?{...f,[key]:value}:f));
 const toggle=(key:'toc_type_ids'|'toc_tournament_ids',value:number)=>set(key,current[key].includes(value)?current[key].filter((x:number)=>x!==value):[...current[key],value]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);const r=await fetch(`/api/admin/tournaments/${id}/relationships`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(current)}),p=await r.json();setBusy(false);if(!r.ok)setMessage(p.error||'Save rejected');else{const flights=(p.record.flights||[]).map((f:Row)=>({...blankFlight(),...f,starts_at:date(f.starts_at),ends_at:date(f.ends_at),registration_starts_at:date(f.registration_starts_at),registration_ends_at:date(f.registration_ends_at)}));setCurrent({...p.record,flights});setMessage('Tournament relationships saved.');}};
 return <form className="configuration-form tournament-relationships" onSubmit={submit}><header><div><span>Relationships</span><h3>Flights, Qualifiers & Tournament of Champions</h3></div><button type="button" onClick={onClose}>Close</button></header>{message&&<p role="status" className="configuration-message">{message}</p>}
 <section><h4>Flight Tournaments</h4><label className="check-field"><input type="checkbox" checked={current.advancing_to_flight_tournaments} onChange={e=>set('advancing_to_flight_tournaments',e.target.checked)}/>Flight Tournaments?</label><label className="check-field"><input type="checkbox" checked={current.allow_search_registration} onChange={e=>set('allow_search_registration',e.target.checked)}/>Direct Registration to Main Tournament</label><label>Chip Accumulator<select value={current.chip_carryover} onChange={e=>set('chip_carryover',e.target.value)}><option value="">Not used</option><option value="highest">Highest stack</option><option value="sum">Sum stacks</option></select></label>{current.flights.map((flight:Row,i:number)=><fieldset key={flight.id||i}><legend>Flight {i+1}{flight.id?' (existing flight — read-only)':''}</legend><div className="configuration-form-grid">{['name','starts_at','ends_at','registration_starts_at','registration_ends_at','minimum_buyin','tournament_fee_percent','initial_chips_count'].map(key=><label key={key}>{({name:'Name',starts_at:'Start Date',ends_at:'End Date',registration_starts_at:'Registration Start Date',registration_ends_at:'Registration End Date',minimum_buyin:'Initial Buy In',tournament_fee_percent:'Charity Take',initial_chips_count:'Initial Chips Count'} as Row)[key]}<input readOnly={Boolean(flight.id)} type={key.includes('_at')?'datetime-local':key==='name'?'text':'number'} value={flight[key]} onChange={e=>updateFlight(i,key,key==='name'||key.includes('_at')?e.target.value:Number(e.target.value))}/></label>)}</div>{!flight.id?<button type="button" className="danger" onClick={()=>set('flights',current.flights.filter((_:Row,n:number)=>n!==i))}>Remove flight</button>:null}</fieldset>)}<button type="button" onClick={()=>set('flights',[...current.flights,blankFlight()])}>Add Flight Tournament</button></section>
 <section><h4>Qualifier Tournament</h4>{current.qualifiers.map((q:Row,i:number)=><div className="configuration-form-grid" key={i}><label>Qualifier Tournament<select value={q.tournament_id} onChange={e=>set('qualifiers',current.qualifiers.map((x:Row,n:number)=>n===i?{...x,tournament_id:Number(e.target.value)}:x))}><option value="">Choose tournament</option>{options.tournaments.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Qualifier Prize<input value={q.qualifier_prize} onChange={e=>set('qualifiers',current.qualifiers.map((x:Row,n:number)=>n===i?{...x,qualifier_prize:e.target.value}:x))}/></label><button type="button" className="danger" onClick={()=>set('qualifiers',current.qualifiers.filter((_:Row,n:number)=>n!==i))}>Remove</button></div>)}<button type="button" onClick={()=>set('qualifiers',[...current.qualifiers,{tournament_id:options.tournaments[0]?.id||0,qualifier_prize:''}])}>Add Qualifier Target</button></section>
 <section><h4>Tournament of Champions Qualifiers</h4><label className="check-field"><input type="checkbox" checked={current.toc_all_types} onChange={e=>set('toc_all_types',e.target.checked)}/>All Tournament Types</label><div className="relationship-matrix"><strong>Tournament Types</strong>{options.types.map(t=><label className="check-field" key={t.id}><input type="checkbox" checked={current.toc_type_ids.includes(t.id)} onChange={()=>toggle('toc_type_ids',t.id)}/>{t.name}</label>)}</div><div className="relationship-matrix"><strong>Specific Tournaments</strong>{options.tournaments.map(t=><label className="check-field" key={t.id}><input type="checkbox" checked={current.toc_tournament_ids.includes(t.id)} onChange={()=>toggle('toc_tournament_ids',t.id)}/>{t.name}</label>)}</div></section><div className="configuration-actions"><button className="primary" disabled={busy}>{busy?'Saving…':'Save Relationships'}</button><button type="button" onClick={onClose}>Cancel</button></div></form>;
}
