'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
type Row=Record<string,any>;
type Options={events:Row[];types:Row[];venues:Row[];blinds:Row[];payouts:Row[]};
const blank=():Row=>({name:'',alias:'',event_id:'',venue_id:'',tournament_type_id:'',blind_structure_id:'',payout_template_id:'',point_distribution_id:'',short_description:'',long_description:'',rules_description:'',starts_at:'',ends_at:'',registration_starts_at:'',registration_ends_at:'',dealer_fee:0,tournament_fee_percent:0,minimum_buyin:0,maximum_buyin:'',allow_rebuy:false,allowed_rebuys_limit:'',rebuy_amount:0,rebuy_fee:0,allow_rebuy_chips:false,rebuy_chips_count:0,initial_chips_count:0,title_count:false,players_at_final_table:'',points_multiplier_enabled:false,points_multiplier_value:'',participation_bonus_points:0,chip_carryover:'',allow_search_registration:true,blind_intervals:'',status:false,featured:false,multi_day:false,logo_url:'',banner_url:'',live_stream_url:'',qualifier_tournament:false,advancing_to_flight_tournaments:false});
const saveFields=Object.keys(blank());
const datetime=(value:unknown)=>typeof value==='string'&&value?value.slice(0,16):'';

export function TournamentManager(){
 const [rows,setRows]=useState<Row[]>([]),[options,setOptions]=useState<Options>({events:[],types:[],venues:[],blinds:[],payouts:[]}),[draft,setDraft]=useState<Row|null>(null),[view,setView]=useState<Row|null>(null),[year,setYear]=useState(''),[eventFilter,setEventFilter]=useState(''),[typeFilter,setTypeFilter]=useState(''),[statusFilter,setStatusFilter]=useState(''),[scope,setScope]=useState(''),[search,setSearch]=useState(''),[sort,setSort]=useState('id'),[direction,setDirection]=useState('desc'),[size,setSize]=useState(10),[page,setPage]=useState(1),[total,setTotal]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const params=new URLSearchParams({year,event:eventFilter,type:typeFilter,status:statusFilter,scope,search,sort,dir:direction,size:String(size),page:String(page)});const response=await fetch(`/api/admin/tournaments?${params}`,{cache:'no-store'});const payload=await response.json();if(response.ok){setRows(payload.records||[]);setOptions(payload.options||options);setTotal(payload.total||0);}else setMessage(payload.error||'Unable to load tournaments');};
 useEffect(()=>{void load();},[year,eventFilter,typeFilter,statusFilter,scope,search,sort,direction,size,page]);
 const openRecord=async(id:number,mode:'edit'|'view')=>{setBusy(true);const response=await fetch(`/api/admin/tournaments?id=${id}`,{cache:'no-store'});const payload=await response.json();setBusy(false);if(!response.ok){setMessage(payload.error||'Tournament unavailable');return;}setOptions(payload.options||options);const record={...blank(),...payload.record,starts_at:datetime(payload.record.starts_at),ends_at:datetime(payload.record.ends_at),registration_starts_at:datetime(payload.record.registration_starts_at),registration_ends_at:datetime(payload.record.registration_ends_at)};if(mode==='edit')setDraft(record);else setView(record);};
 const values=()=>Object.fromEntries(saveFields.map((key)=>[key,draft?.[key]??blank()[key]]));
 const submit=async(event:FormEvent)=>{event.preventDefault();if(!draft)return;setBusy(true);const response=await fetch('/api/admin/tournaments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'save',...(draft.id?{id:draft.id}:{}),values:values()})});const payload=await response.json();setBusy(false);if(!response.ok){setMessage(payload.error||'Save rejected');return;}setMessage(draft.id?'Tournament updated.':'Tournament created.');setDraft(null);await load();};
 const act=async(action:'copy'|'status'|'delete',row:Row,statusValue?:boolean)=>{setBusy(true);const body=action==='status'?{action,id:row.id,status:statusValue}:{action,id:row.id};const response=await fetch('/api/admin/tournaments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const payload=await response.json();setBusy(false);if(!response.ok){setMessage(payload.error||'Change rejected');return;}setMessage(action==='copy'?'Unpublished copy created without entries, add-ons, payouts, or updates.':'Tournament updated.');await load();};
 const set=(key:string,value:unknown)=>setDraft((current)=>current?{...current,[key]:value}:current);
 const input=(label:string,key:string,type='text',min?:number)=><label>{label}<input name={key} type={type} min={min} value={draft?.[key]??''} onChange={(event)=>set(key,type==='number'?(event.target.value===''?'':Number(event.target.value)):event.target.value)}/></label>;
 const check=(label:string,key:string)=><label className="check-field"><input type="checkbox" checked={Boolean(draft?.[key])} onChange={(event)=>set(key,event.target.checked)}/>{label}</label>;
 const select=(label:string,key:string,items:Row[],optional=true)=><label>{label}<select value={draft?.[key]??''} onChange={(event)=>set(key,event.target.value?Number(event.target.value):'')}>{optional?<option value="">Not selected</option>:<option value="">Select…</option>}{items.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>;
 const reset=()=>{setYear('');setEventFilter('');setTypeFilter('');setStatusFilter('');setScope('');setSearch('');setPage(1);};
 const sortBy=(field:string)=>{setDirection(sort===field&&direction==='asc'?'desc':'asc');setSort(field);};
 return <div className="configuration-manager">
  <div className="configuration-toolbar"><h3>Tournaments List</h3><button className="primary" onClick={()=>setDraft(blank())}>＋ Create</button><label>Year<input value={year} placeholder="All years" inputMode="numeric" onChange={(event)=>{setYear(event.target.value);setPage(1);}}/></label><label>Event<select value={eventFilter} onChange={(event)=>{setEventFilter(event.target.value);setPage(1);}}><option value="">All events</option>{options.events.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Type<select value={typeFilter} onChange={(event)=>{setTypeFilter(event.target.value);setPage(1);}}><option value="">All types</option>{options.types.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Status<select value={statusFilter} onChange={(event)=>{setStatusFilter(event.target.value);setPage(1);}}><option value="">Any status</option><option value="published">Published</option><option value="unpublished">Unpublished</option></select></label><label>Scope<select value={scope} onChange={(event)=>{setScope(event.target.value);setPage(1);}}><option value="">All tournaments</option><option value="featured">Featured</option><option value="standard">Not featured</option></select></label><label>Search<input value={search} onChange={(event)=>{setSearch(event.target.value);setPage(1);}}/></label><button onClick={reset}>Reset</button><label>Show<select value={size} onChange={(event)=>{setSize(Number(event.target.value));setPage(1);}}>{[10,25,50,100].map((count)=><option key={count}>{count}</option>)}</select></label></div>
  {message?<p role="status" className="configuration-message">{message}</p>:null}
  {draft?<form className="configuration-form tournament-setup-form" onSubmit={submit}><header><div><span>{draft.id?'Edit tournament':'Create tournament'}</span><h3>{draft.name||'Tournament setup'}</h3></div><div className="configuration-actions">{draft.id?<><button type="button" onClick={()=>void act('copy',draft)}>Save as Copy</button><Link className="edit" href={`/admin/tournaments/${draft.id}`}>Manage Tournament</Link></>:null}<button type="button" onClick={()=>setDraft(null)}>Cancel</button></div></header>
   <section id="basicinfo"><h4>Basic Information</h4><div className="configuration-form-grid"><label>Status<select value={String(draft.status)} onChange={(event)=>set('status',event.target.value==='true')}><option value="true">Published</option><option value="false">Unpublished</option></select></label>{check('Featured','featured')}{select('Tournament Type *','tournament_type_id',options.types,false)}{select('Point Distribution','point_distribution_id',options.payouts)}{select('Event','event_id',options.events)}{select('Venue','venue_id',options.venues)}{input('Name *','name')}<label>Short Description<textarea value={draft.short_description||''} onChange={(event)=>set('short_description',event.target.value)}/></label><label>Long Description<textarea value={draft.long_description||''} onChange={(event)=>set('long_description',event.target.value)}/></label>{input('Live Stream YouTube URL','live_stream_url','url')}{input('Logo URL','logo_url','url')}{input('Banner Image URL','banner_url','url')}{check('Multi-day','multi_day')}{input('Start Date','starts_at','datetime-local')}{input('End Date','ends_at','datetime-local')}{input('Registration Start Date','registration_starts_at','datetime-local')}{input('Registration End Date','registration_ends_at','datetime-local')}</div></section>
   <section id="structurespay"><h4>Structures and Payout</h4><div className="configuration-form-grid">{select('Blind Structure','blind_structure_id',options.blinds)}{select('Payout Distribution','payout_template_id',options.payouts)}{input('Blind Intervals','blind_intervals','number',1)}{input('Initial Buy In','minimum_buyin','number',0)}{input('Dealer Appreciation Fee','dealer_fee','number',0)}{input('Charity Take','tournament_fee_percent','number',0)}{input('Initial Chips Count','initial_chips_count','number',0)}{input('Maximum Buy In','maximum_buyin','number',0)}{check('Allow Rebuy','allow_rebuy')}{input('Allowed Rebuys Limit','allowed_rebuys_limit','number',0)}{input('Rebuy Amount','rebuy_amount','number',0)}{input('Rebuy Dealer Appreciation Fee','rebuy_fee','number',0)}{check('Allow Rebuy Chips','allow_rebuy_chips')}{input('Rebuy Chips Count','rebuy_chips_count','number',0)}</div></section>
   <section id="scoring"><h4>Scoring and Qualification</h4><div className="configuration-form-grid">{check('Title Count','title_count')}{input('Participation Bonus Points','participation_bonus_points','number',0)}{check('Points Multiplier','points_multiplier_enabled')}{input('Points Multiplier Value','points_multiplier_value','number',0)}{input('Players at Final Table','players_at_final_table','number',2)}<label>Chip Accumulator<select value={draft.chip_carryover||''} onChange={(event)=>set('chip_carryover',event.target.value)}><option value="">Not used</option><option value="highest">Highest stack</option><option value="sum">Sum stacks</option></select></label>{check('Allow Search Registration','allow_search_registration')}{check('Qualifier Tournament','qualifier_tournament')}{check('Advancing to Flight Tournament','advancing_to_flight_tournaments')}<label>Rules Description<textarea value={draft.rules_description||''} onChange={(event)=>set('rules_description',event.target.value)}/></label></div></section>
   <div className="configuration-actions"><button className="primary" disabled={busy}>{busy?'Saving…':draft.id?'Update':'Create'}</button><button type="button" onClick={()=>setDraft(null)}>Cancel</button></div>
  </form>:null}
  {view?<section className="configuration-form"><header><h3>{view.name}</h3><button onClick={()=>setView(null)}>Close</button></header><div className="configuration-form-grid"><p><strong>Event:</strong> {options.events.find((item)=>item.id===view.event_id)?.name||'—'}</p><p><strong>Type:</strong> {options.types.find((item)=>item.id===view.tournament_type_id)?.name||'—'}</p><p><strong>Dates:</strong> {view.starts_at||'—'} — {view.ends_at||'—'}</p><p><strong>Buy-in:</strong> ${view.minimum_buyin||0}</p><p><strong>Status:</strong> {view.status?'Published':'Unpublished'}</p><p><strong>Rules:</strong> {view.rules_description||'—'}</p></div></section>:null}
  <div className="dpt-admin-table-wrap"><table className="dpt-admin-table"><thead><tr><th><button onClick={()=>sortBy('id')}>#</button></th><th><button onClick={()=>sortBy('name')}>Name</button></th><th>Event</th><th>Type</th><th><button onClick={()=>sortBy('starts_at')}>Start Date</button></th><th><button onClick={()=>sortBy('ends_at')}>End Date</button></th><th><button onClick={()=>sortBy('status')}>Status</button></th><th>Actions</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id}><td>{row.id}</td><td>{row.name}</td><td>{row.event?.name||'—'}</td><td>{row.tournament_type?.name||'—'}</td><td>{row.starts_at?new Date(row.starts_at).toLocaleString():'—'}</td><td>{row.ends_at?new Date(row.ends_at).toLocaleString():'—'}</td><td>{row.status?'Published':'Unpublished'}</td><td className="configuration-actions"><button className="edit" onClick={()=>void openRecord(row.id,'edit')}>Edit</button><button className="view" onClick={()=>void openRecord(row.id,'view')}>View</button><Link href={`/admin/tournaments/${row.id}`}>Manage</Link>{row.alias?<Link href={`/tournaments/${row.alias}`}>Public</Link>:null}<button onClick={()=>void act('copy',row)}>Copy</button><button onClick={()=>void act('status',row,!row.status)}>{row.status?'Unpublish':'Publish'}</button><button className="danger" onClick={()=>{if(confirm('Delete this unpublished tournament? Runtime data blocks deletion.'))void act('delete',row);}}>Delete</button></td></tr>)}</tbody></table></div>
  <div className="players-pagination"><span>Showing {total?(page-1)*size+1:0} to {Math.min(page*size,total)} of {total} entries</span><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><strong>{page}</strong><button disabled={page*size>=total} onClick={()=>setPage(page+1)}>Next</button></div>
 </div>;
}
