import {NextRequest,NextResponse} from 'next/server';
import {dptAdminSupabaseFetch,getDptAdminApiContext} from '../../../../../lib/dpt-admin-api';
export const dynamic='force-dynamic';
const specs={
 articles:{table:'articles',rpc:'dpt_admin_save_article_with_media',deleteRpc:'dpt_admin_delete_article',select:'id,title,alias,status,category_id,tournament_id,published_at,featured,logo_media_id,intro_html,body_html,video_url,seo_title,seo_description,article_profiles(profile_id,profiles(first_name,last_name,nick_name))',fields:['title','alias','status','category_id','tournament_id','published_at','featured','logo_media_id','intro_html','body_html','video_url','seo_title','seo_description','profile_ids']},
 categories:{table:'article_categories',rpc:'dpt_admin_save_category',deleteRpc:'dpt_admin_delete_category',select:'id,title,alias,status,parent_id,description,seo_title,seo_description,created_at',fields:['title','alias','status','parent_id','description','seo_title','seo_description']},
 emailtemplates:{table:'email_templates',rpc:'dpt_admin_save_email_template_with_attachments',copyRpc:'dpt_admin_copy_email_template',deleteRpc:'dpt_admin_archive_email_template',select:'id,title,subject,body_html,status,template_type,allowed_variables,updated_at,email_template_attachments(media_id)',fields:['title','subject','body_html','status','template_type','allowed_variables','media_ids']},
} as const;
type Resource=keyof typeof specs;
const isResource=(value:string):value is Resource=>value in specs;
const object=(value:unknown):value is Record<string,unknown>=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value);
const exact=(value:Record<string,unknown>,keys:string[])=>Object.keys(value).every((key)=>keys.includes(key));
const uuid=(value:unknown)=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const uniqueUuidArray=(value:unknown)=>Array.isArray(value)&&value.every(uuid)&&new Set(value).size===value.length;
export async function GET(request:NextRequest,{params}:{params:{resource:string}}){
 const context=await getDptAdminApiContext();if(!context)return NextResponse.json({error:'Unauthorized'},{status:401});if(!isResource(params.resource))return NextResponse.json({error:'Unknown content resource'},{status:404});
 const spec=specs[params.resource],q=request.nextUrl.searchParams,page=Math.max(1,Number(q.get('page')||1)),size=[10,25,50,100].includes(Number(q.get('size')))?Number(q.get('size')):10,filters=[`order=${params.resource==='emailtemplates'?'updated_at':'id'}.desc`,`limit=${size}`,`offset=${(page-1)*size}`];if(q.get('search'))filters.push(`title=ilike.*${encodeURIComponent(q.get('search')!.trim())}*`);
 const calls=[dptAdminSupabaseFetch(context,`/rest/v1/${spec.table}?select=${encodeURIComponent(spec.select)}&${filters.join('&')}`,{headers:{Prefer:'count=exact'}})];if(params.resource==='articles')calls.push(dptAdminSupabaseFetch(context,'/rest/v1/article_categories?select=id,title&status=eq.true&order=title.asc'),dptAdminSupabaseFetch(context,'/rest/v1/tournaments?select=id,name&deleted_at=is.null&order=starts_at.desc&limit=500'));else if(params.resource==='categories')calls.push(dptAdminSupabaseFetch(context,'/rest/v1/article_categories?select=id,title&order=title.asc'));
 const responses=await Promise.all(calls);if(responses.some((response)=>!response.ok))return NextResponse.json({error:'Content list unavailable'},{status:502});const options=params.resource==='articles'?{categories:await responses[1].json(),tournaments:await responses[2].json()}:params.resource==='categories'?{categories:await responses[1].json()}:{};return NextResponse.json({records:await responses[0].json(),total:Number(responses[0].headers.get('content-range')?.split('/')[1]||0),options});
}
export async function POST(request:NextRequest,{params}:{params:{resource:string}}){
 const context=await getDptAdminApiContext();if(!context)return NextResponse.json({error:'Unauthorized'},{status:401});if(!isResource(params.resource))return NextResponse.json({error:'Unknown content resource'},{status:404});let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>}catch{return NextResponse.json({error:'Invalid JSON body'},{status:400})}
 const spec=specs[params.resource],id=body.id===null||body.id===undefined?null:body.id,validId=(typeof id==='number'&&Number.isSafeInteger(id)&&id>0)||uuid(id);
 if(body.action==='save'&&exact(body,['action','id','values'])&&(id===null||validId)&&object(body.values)){
  const values=body.values;if(Object.keys(values).some((key)=>!spec.fields.includes(key as never))||typeof values.title!=='string'||!values.title.trim())return NextResponse.json({error:'Invalid content payload'},{status:400});
  if(params.resource==='categories'&&typeof values.status!=='boolean')return NextResponse.json({error:'Invalid category status'},{status:400});
  if(params.resource==='articles'&&(typeof values.featured!=='boolean'||!['draft','published','archived'].includes(String(values.status))||!uniqueUuidArray(values.profile_ids)||(values.logo_media_id!==null&&values.logo_media_id!==''&&!uuid(values.logo_media_id))))return NextResponse.json({error:'Invalid article state'},{status:400});
  if(params.resource==='emailtemplates'&&(!['draft','published','archived'].includes(String(values.status))||!['system','user'].includes(String(values.template_type))||!Array.isArray(values.allowed_variables)||!values.allowed_variables.every((item)=>typeof item==='string')||!uniqueUuidArray(values.media_ids)))return NextResponse.json({error:'Invalid template state'},{status:400});
  const persistence={...values};delete persistence.logo_media_id;delete persistence.media_ids;let payload:Record<string,unknown>={p_id:id,p_values:persistence};if(params.resource==='articles')payload={...payload,p_logo_media_id:values.logo_media_id||null};if(params.resource==='emailtemplates')payload={...payload,p_media_ids:values.media_ids};
  const response=await dptAdminSupabaseFetch(context,`/rest/v1/rpc/${spec.rpc}`,{method:'POST',body:JSON.stringify(payload)});if(!response.ok)return NextResponse.json({error:'Content save rejected',detail:await response.text()},{status:409});return NextResponse.json({record:await response.json()},{status:id===null?201:200});
 }
 if(body.action==='copy'&&exact(body,['action','id'])&&validId&&'copyRpc'in spec){const response=await dptAdminSupabaseFetch(context,`/rest/v1/rpc/${spec.copyRpc}`,{method:'POST',body:JSON.stringify({p_id:id})});if(!response.ok)return NextResponse.json({error:'Copy rejected'},{status:409});return NextResponse.json({record:await response.json()},{status:201});}
 if(body.action==='delete'&&exact(body,['action','id'])&&validId&&spec.deleteRpc){const response=await dptAdminSupabaseFetch(context,`/rest/v1/rpc/${spec.deleteRpc}`,{method:'POST',body:JSON.stringify({p_id:id})});if(!response.ok)return NextResponse.json({error:'Delete rejected'},{status:409});return NextResponse.json({record:await response.json()});}
 return NextResponse.json({error:'Invalid content request'},{status:400});
}
