import {NextRequest,NextResponse} from 'next/server';
import {dptAdminSupabaseFetch,getDptAdminApiContext} from '../../../../lib/dpt-admin-api';
export const dynamic='force-dynamic';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const targetKeys=['venue_ids','season_ids','event_ids','league_ids','tournament_ids','role_names'] as const;
const exact=(value:Record<string,unknown>,keys:string[])=>Object.keys(value).every((key)=>keys.includes(key));
export async function GET(){
 const context=await getDptAdminApiContext();if(!context)return NextResponse.json({error:'Unauthorized'},{status:401});
 const calls=[dptAdminSupabaseFetch(context,'/rest/v1/notification_campaigns?select=id,title,status,purpose,created_at,sender_profile_id,target,external_delivery_mode&order=created_at.desc&limit=100'),dptAdminSupabaseFetch(context,'/rest/v1/venues?select=id,name&status=eq.true&deleted_at=is.null&order=name.asc'),dptAdminSupabaseFetch(context,'/rest/v1/seasons?select=id,name&status=eq.true&deleted_at=is.null&order=name.asc'),dptAdminSupabaseFetch(context,'/rest/v1/events?select=id,name&status=eq.true&deleted_at=is.null&order=name.asc'),dptAdminSupabaseFetch(context,'/rest/v1/leagues?select=id,name&status=eq.true&deleted_at=is.null&order=name.asc'),dptAdminSupabaseFetch(context,'/rest/v1/tournaments?select=id,name&deleted_at=is.null&order=starts_at.desc&limit=500'),dptAdminSupabaseFetch(context,'/rest/v1/admin_roles?select=name,display_name&order=display_name.asc')];
 const [campaigns,...rest]=await Promise.all(calls);if(!campaigns.ok||rest.some((response)=>!response.ok))return NextResponse.json({error:'Campaign catalog unavailable'},{status:502});return NextResponse.json({records:await campaigns.json(),options:{venues:await rest[0].json(),seasons:await rest[1].json(),events:await rest[2].json(),leagues:await rest[3].json(),tournaments:await rest[4].json(),roles:await rest[5].json()}});
}
export async function POST(request:NextRequest){
 const context=await getDptAdminApiContext();if(!context)return NextResponse.json({error:'Unauthorized'},{status:401});let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>}catch{return NextResponse.json({error:'Invalid JSON'},{status:400})}
 if(!exact(body,['values','idempotency_key'])||typeof body.idempotency_key!=='string'||!uuid.test(body.idempotency_key)||!body.values||typeof body.values!=='object'||Array.isArray(body.values))return NextResponse.json({error:'Invalid notification request'},{status:400});const values=body.values as Record<string,unknown>;
 if(!exact(values,['title','message_html','purpose','email_enabled','sms_enabled','sms_body','profile_ids','target','dry_run'])||typeof values.title!=='string'||typeof values.message_html!=='string'||!values.title.trim()||!values.message_html.trim()||!['general','tournament_update','marketing'].includes(String(values.purpose))||typeof values.email_enabled!=='boolean'||typeof values.sms_enabled!=='boolean'||typeof values.sms_body!=='string'||typeof values.dry_run!=='boolean'||!Array.isArray(values.profile_ids)||values.profile_ids.some((id)=>typeof id!=='string'||!uuid.test(id))||new Set(values.profile_ids).size!==values.profile_ids.length||!values.target||typeof values.target!=='object'||Array.isArray(values.target))return NextResponse.json({error:'Invalid notification fields'},{status:400});
 const target=values.target as Record<string,unknown>;if(!exact(target,[...targetKeys])||targetKeys.some((key)=>!Array.isArray(target[key])))return NextResponse.json({error:'Invalid notification targets'},{status:400});for(const key of targetKeys){const list=target[key] as unknown[];if(new Set(list).size!==list.length||(key==='role_names'?list.some((item)=>typeof item!=='string'||!/^[a-z_]+$/.test(item)):list.some((item)=>typeof item!=='number'||!Number.isSafeInteger(item)||item<1)))return NextResponse.json({error:'Invalid notification targets'},{status:400});}
 const response=await dptAdminSupabaseFetch(context,'/rest/v1/rpc/dpt_admin_create_notification',{method:'POST',body:JSON.stringify({p_values:values,p_idempotency:body.idempotency_key})});if(!response.ok)return NextResponse.json({error:'Notification rejected',detail:await response.text()},{status:409});return NextResponse.json({campaign:await response.json()},{status:values.dry_run?200:201});
}
