#!/usr/bin/env python3
"""Generate local Supabase/Postgres seed SQL for DPT public data.

Input:
- apps/site/data/dpt-public.json
- apps/site/data/dpt-media-manifest.json

Output:
- supabase/seed/dpt_public_seed.sql

Local-only. Does not connect to Supabase or mutate any database.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any
import json

ROOT = Path(__file__).resolve().parents[1]
DATA_PATH = ROOT / 'apps/site/data/dpt-public.json'
MEDIA_PATH = ROOT / 'apps/site/data/dpt-media-manifest.json'
OUT_PATH = ROOT / 'supabase/seed/dpt_public_seed.sql'


def q(value: Any) -> str:
    if value is None:
        return 'null'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    return "'" + text.replace("'", "''") + "'"


def qdate(value: Any) -> str:
    if not value:
        return 'null'
    return q(str(value)[:10])


def qts(value: Any) -> str:
    if not value:
        return 'null'
    return q(str(value))


def qjson(value: Any) -> str:
    return q(json.dumps(value, ensure_ascii=False, separators=(',', ':'))) + '::jsonb'


def local_for(media_by_source: dict[str, dict[str, Any]], source_url: str | None) -> str:
    if not source_url:
        return ''
    item = media_by_source.get(source_url) or {}
    return item.get('localPublicPath') or ''


def insert(table: str, columns: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return ''
    values = ',\n'.join('  (' + ', '.join(row) + ')' for row in rows)
    return f"insert into public.{table} ({', '.join(columns)}) values\n{values}\non conflict do nothing;\n"


def main() -> None:
    data = json.loads(DATA_PATH.read_text())
    media = json.loads(MEDIA_PATH.read_text())
    media_by_source = {asset['sourceUrl']: asset for asset in media.get('assets', [])}

    lines = [
        '-- Generated by scripts/build_dpt_supabase_seed.py',
        '-- Local Supabase/Postgres seed for SQL-backed DPT public replacement data.',
        '-- Safe to inspect; do not run against production without review.',
        '',
        'begin;',
        'set session_replication_role = replica;',
        "truncate table public.dpt_media_assets, public.dpt_public_videos, public.dpt_public_champions, public.dpt_public_leaderboard_entries, public.dpt_public_players, public.dpt_public_articles, public.dpt_public_tournaments, public.dpt_public_events, public.dpt_public_venues restart identity cascade;",
        'set session_replication_role = DEFAULT;',
        '',
    ]

    venue_rows = []
    for v in data.get('venues', []):
        venue_rows.append([
            q(v.get('id')), q(v.get('alias')), q(v.get('name')), q(v.get('city')), q(v.get('state')), q(v.get('address')),
            q(v.get('imageUrl')), q(local_for(media_by_source, v.get('imageUrl'))), qjson(v)
        ])
    lines.append(insert('dpt_public_venues', ['legacy_id','alias','name','city','state','address','image_url','local_image_path','raw'], venue_rows))

    event_rows = []
    for e in data.get('events', []):
        venue_id = (e.get('venue') or {}).get('id')
        event_rows.append([
            q(e.get('id')), q(e.get('alias')), q(e.get('name')), q(e.get('description')), qdate(e.get('startDate')), qdate(e.get('endDate')),
            q(venue_id), q(e.get('imageUrl')), q(local_for(media_by_source, e.get('imageUrl'))), qjson(e)
        ])
    lines.append(insert('dpt_public_events', ['legacy_id','alias','name','description','start_date','end_date','venue_legacy_id','image_url','local_image_path','raw'], event_rows))

    tournament_rows = []
    for t in data.get('tournaments', []):
        venue_id = (t.get('venue') or {}).get('id')
        event_alias = (t.get('event') or {}).get('alias')
        tournament_rows.append([
            q(t.get('id')), q(t.get('alias')), q(event_alias), q(t.get('name')), q(t.get('shortDescription')),
            qdate(t.get('startDate')), qdate(t.get('endDate')), q(venue_id), q(t.get('minimumBuyIn')),
            q(t.get('totalPlayers')), q(t.get('totalPrizePool')), q(t.get('imageUrl')), q(local_for(media_by_source, t.get('imageUrl'))), qjson(t)
        ])
    lines.append(insert('dpt_public_tournaments', ['legacy_id','alias','event_alias','name','short_description','start_date','end_date','venue_legacy_id','minimum_buy_in','total_players','total_prize_pool','image_url','local_image_path','raw'], tournament_rows))

    article_rows = []
    for a in data.get('articles', []):
        event_alias = (a.get('event') or {}).get('alias')
        tournament_alias = (a.get('tournament') or {}).get('alias')
        article_rows.append([
            q(a.get('id')), q(a.get('alias')), q(a.get('title')), q(a.get('excerpt')), qts(a.get('publishedAt')),
            q(event_alias), q(tournament_alias), q(a.get('imageUrl')), q(local_for(media_by_source, a.get('imageUrl'))), q(a.get('videoUrl')), qjson(a)
        ])
    lines.append(insert('dpt_public_articles', ['legacy_id','alias','title','excerpt','published_at','event_alias','tournament_alias','image_url','local_image_path','video_url','raw'], article_rows))

    player_seen = set()
    player_rows = []
    leaderboard_rows = []
    for l in data.get('leaderboard', []):
        pid = l.get('playerId')
        if pid not in player_seen:
            player_seen.add(pid)
            player_rows.append([
                q(pid), q(l.get('name')), q(l.get('city')), q(l.get('state')), q(l.get('avatarUrl')), q(local_for(media_by_source, l.get('avatarUrl'))), qjson(l)
            ])
        leaderboard_rows.append([
            q(l.get('rank')), q(pid), q(l.get('name')), q(l.get('points')), q(l.get('wins')), q(l.get('cashes')), q(l.get('city')), q(l.get('state')), qjson(l)
        ])
    lines.append(insert('dpt_public_players', ['legacy_id','display_name','city','state','avatar_url','local_avatar_path','raw'], player_rows))
    lines.append(insert('dpt_public_leaderboard_entries', ['rank','player_legacy_id','display_name','points','wins','cashes','city','state','raw'], leaderboard_rows))

    champion_rows = []
    for c in data.get('champions', []):
        champion_rows.append([
            q(c.get('tournamentAlias')), q(c.get('tournament')), q(c.get('player')), q(c.get('finish')), q(c.get('winnings')), qdate(c.get('date')), qjson(c)
        ])
    lines.append(insert('dpt_public_champions', ['tournament_alias','tournament_name','player_name','finish','winnings','result_date','raw'], champion_rows))

    video_rows = []
    for v in data.get('videos', []):
        video_rows.append([
            q('video-' + str(v.get('embedUrl') or v.get('videoUrl'))), q(v.get('title')), q(v.get('videoUrl')), q(v.get('embedUrl')),
            q(v.get('thumbnailUrl')), q(v.get('thumbnailUrl')), q(v.get('source')), qjson(v)
        ])
    lines.append(insert('dpt_public_videos', ['id','title','video_url','embed_url','thumbnail_url','local_thumbnail_path','source','raw'], video_rows))

    media_rows = []
    for a in media.get('assets', []):
        media_rows.append([
            q(a.get('sourceUrl')), q(a.get('assetType')), q(a.get('filename')), q(a.get('suggestedPublicPath')), q(a.get('localPublicPath')),
            q(a.get('status')), q(a.get('contentType')), q(a.get('contentLength')), q(bool(a.get('downloaded'))), qjson(a.get('references') or []), qjson(a)
        ])
    lines.append(insert('dpt_media_assets', ['source_url','asset_type','filename','suggested_public_path','local_public_path','status','content_type','content_length','downloaded','asset_references','raw'], media_rows))

    lines += ['commit;', '']
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text('\n'.join(lines))
    print(json.dumps({
        'out': str(OUT_PATH),
        'venues': len(venue_rows),
        'events': len(event_rows),
        'tournaments': len(tournament_rows),
        'articles': len(article_rows),
        'players': len(player_rows),
        'leaderboard': len(leaderboard_rows),
        'champions': len(champion_rows),
        'videos': len(video_rows),
        'mediaAssets': len(media_rows),
    }, indent=2))


if __name__ == '__main__':
    main()
