-- DPT Rebuild Lab initial Supabase schema
-- Draft/dev migration only. Do not run against production without review.

create extension if not exists pgcrypto;

create type public.tournament_type_code as enum ('dpt_standard', 'satellite', 'freeroll', 'flight');
create type public.chip_carryover_mode as enum ('highest', 'sum');
create type public.app_role as enum ('super_admin', 'administrator', 'host', 'venue', 'user');

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  legacy_user_id bigint unique,
  first_name text,
  last_name text,
  nick_name text,
  email text unique,
  mobile text,
  country_code text,
  alias text unique,
  avatar_url text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.profile_roles (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role public.app_role not null,
  created_at timestamptz not null default now(),
  primary key (profile_id, role)
);

create table public.leagues (
  id bigint generated by default as identity primary key,
  name text not null,
  alias text unique,
  description text,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.seasons (
  id bigint generated by default as identity primary key,
  league_id bigint references public.leagues(id),
  name text not null,
  alias text unique,
  description text,
  is_default boolean not null default false,
  start_at timestamptz,
  end_at timestamptz,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.venues (
  id bigint generated by default as identity primary key,
  name text not null,
  alias text unique,
  address text,
  city text,
  state text,
  zip text,
  phone text,
  website text,
  latitude numeric,
  longitude numeric,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.events (
  id bigint generated by default as identity primary key,
  season_id bigint references public.seasons(id),
  venue_id bigint references public.venues(id),
  name text not null,
  alias text unique,
  description text,
  start_at timestamptz,
  end_at timestamptz,
  status boolean not null default true,
  rules_description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.tournament_types (
  id bigint generated by default as identity primary key,
  code public.tournament_type_code not null unique,
  name text not null,
  config jsonb not null default '{}'::jsonb
);

create table public.blind_structures (
  id bigint generated by default as identity primary key,
  name text not null,
  blind_info jsonb not null default '[]'::jsonb,
  blind_intervals integer,
  is_copy boolean not null default false,
  status boolean not null default true,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.tournaments (
  id bigint generated by default as identity primary key,
  event_id bigint references public.events(id),
  venue_id bigint references public.venues(id),
  tournament_type_id bigint references public.tournament_types(id),
  main_tournament_id bigint references public.tournaments(id),
  blind_structure_id bigint references public.blind_structures(id),
  name text not null,
  alias text unique,
  short_description text,
  long_description text,
  rules_description text,
  starts_at timestamptz,
  ends_at timestamptz,
  registration_starts_at timestamptz,
  registration_ends_at timestamptz,
  registration_closed boolean not null default false,
  registration_closed_by uuid references public.profiles(id),
  registration_closed_at timestamptz,
  dealer_fee integer not null default 0,
  tournament_fee_percent numeric not null default 0,
  minimum_buyin integer not null default 0,
  maximum_buyin integer,
  allow_rebuy boolean not null default false,
  rebuy_amount integer not null default 0,
  rebuy_fee integer not null default 0,
  rebuy_chips_count integer not null default 0,
  initial_chips_count integer not null default 0,
  players_at_final_table integer,
  points_multiplier_enabled boolean not null default false,
  points_multiplier_value numeric,
  participation_bonus_points integer not null default 0,
  chip_carryover public.chip_carryover_mode,
  allow_search_registration boolean not null default true,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.tournament_qualifiers (
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  qualifier_tournament_id bigint not null references public.tournaments(id) on delete cascade,
  qualifier_prize text,
  primary key (tournament_id, qualifier_tournament_id)
);

create table public.toc_qualified_types (
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  tournament_type_id bigint not null references public.tournament_types(id) on delete cascade,
  primary key (tournament_id, tournament_type_id)
);

create table public.toc_qualified_tournaments (
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  qualified_tournament_id bigint not null references public.tournaments(id) on delete cascade,
  primary key (tournament_id, qualified_tournament_id)
);

create table public.tournament_entries (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  player_id uuid not null references public.profiles(id),
  pre_registered boolean not null default false,
  checked_in boolean not null default false,
  checked_in_by uuid references public.profiles(id),
  initial_buyin integer not null default 0,
  initial_chips_count integer not null default 0,
  total_buy_in_amount integer not null default 0,
  no_of_addons_buy integer not null default 0,
  total_addon_chips integer not null default 0,
  total_chips integer not null default 0,
  rank integer,
  winnings integer,
  score integer,
  bounty integer not null default 0,
  eliminated boolean not null default false,
  elimination_sequence integer,
  final_table boolean not null default false,
  duplicate_status boolean not null default true,
  qualified_flight_player boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  unique(tournament_id, player_id)
);

create table public.tournament_entry_addons (
  id bigint generated by default as identity primary key,
  tournament_entry_id bigint not null references public.tournament_entries(id) on delete cascade,
  addon_buy_in_amount integer not null default 0,
  addon_chips_count integer not null default 0,
  addon_count integer not null default 1,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.payout_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  tournament_type_id bigint references public.tournament_types(id),
  type text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table public.payout_template_rows (
  id bigint generated by default as identity primary key,
  payout_template_id bigint not null references public.payout_templates(id) on delete cascade,
  player_count_start integer,
  player_count_end integer,
  winners_count integer,
  standing integer not null,
  payout_percentage numeric,
  payout_amount integer,
  prize_description text,
  points integer,
  created_at timestamptz not null default now()
);

create table public.tournament_payouts (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete cascade,
  payout_template_row_id bigint references public.payout_template_rows(id),
  standing integer not null,
  payout_percentage numeric,
  payout_amount integer not null default 0,
  prize_description text,
  points integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.flight_advancements (
  id bigint generated by default as identity primary key,
  flight_tournament_id bigint not null references public.tournaments(id) on delete cascade,
  main_tournament_id bigint not null references public.tournaments(id) on delete cascade,
  player_id uuid not null references public.profiles(id),
  chips_advanced integer not null,
  mode_snapshot public.chip_carryover_mode not null,
  advanced_at timestamptz not null default now(),
  undone_at timestamptz,
  unique(flight_tournament_id, main_tournament_id, player_id, advanced_at)
);

create table public.tournament_updates (
  id bigint generated by default as identity primary key,
  tournament_id bigint references public.tournaments(id) on delete cascade,
  title text,
  description text,
  update_at timestamptz,
  image_url text,
  video_url text,
  featured boolean not null default false,
  status boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create index idx_tournaments_event on public.tournaments(event_id);
create index idx_tournaments_type on public.tournaments(tournament_type_id);
create index idx_tournaments_main on public.tournaments(main_tournament_id);
create index idx_tournament_entries_tournament on public.tournament_entries(tournament_id);
create index idx_tournament_entries_player on public.tournament_entries(player_id);
create index idx_tournament_entries_rank on public.tournament_entries(tournament_id, rank);
create index idx_flight_advancements_player on public.flight_advancements(player_id);

create trigger set_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger set_leagues_updated_at before update on public.leagues for each row execute function public.set_updated_at();
create trigger set_seasons_updated_at before update on public.seasons for each row execute function public.set_updated_at();
create trigger set_venues_updated_at before update on public.venues for each row execute function public.set_updated_at();
create trigger set_events_updated_at before update on public.events for each row execute function public.set_updated_at();
create trigger set_blind_structures_updated_at before update on public.blind_structures for each row execute function public.set_updated_at();
create trigger set_tournaments_updated_at before update on public.tournaments for each row execute function public.set_updated_at();
create trigger set_tournament_entries_updated_at before update on public.tournament_entries for each row execute function public.set_updated_at();
create trigger set_payout_templates_updated_at before update on public.payout_templates for each row execute function public.set_updated_at();
create trigger set_tournament_payouts_updated_at before update on public.tournament_payouts for each row execute function public.set_updated_at();
create trigger set_tournament_updates_updated_at before update on public.tournament_updates for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.profile_roles enable row level security;
alter table public.leagues enable row level security;
alter table public.seasons enable row level security;
alter table public.venues enable row level security;
alter table public.events enable row level security;
alter table public.tournament_types enable row level security;
alter table public.blind_structures enable row level security;
alter table public.tournaments enable row level security;
alter table public.tournament_entries enable row level security;
alter table public.tournament_entry_addons enable row level security;
alter table public.payout_templates enable row level security;
alter table public.payout_template_rows enable row level security;
alter table public.tournament_payouts enable row level security;
alter table public.flight_advancements enable row level security;
alter table public.tournament_updates enable row level security;
