begin;

-- Local/staging operational content model.  No delivery worker is created here: campaigns
-- are recorded as queued/dry-run only and external transport credentials are never stored.
insert into public.admin_permissions(name, display_name) values
 ('manage_articles','Articles'), ('manage_categories','Categories'),
 ('manage_email_templates','Email Templates'), ('read_internal_notifications','Internal Inbox')
on conflict (name) do nothing;
insert into public.admin_role_permissions(role_id,permission_id)
select r.id,p.id from public.admin_roles r cross join public.admin_permissions p
where r.name in ('super_admin','administrator') and p.name in ('manage_articles','manage_categories','manage_email_templates','read_internal_notifications')
on conflict do nothing;

create table if not exists public.article_categories (
 id bigint generated by default as identity primary key,
 status boolean not null default true, title text not null, alias text not null unique,
 parent_id bigint references public.article_categories(id) on delete restrict,
 description text, seo_title text, seo_description text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 check (btrim(title) <> '' and btrim(alias) <> '' and alias ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);
create table if not exists public.media_assets (
 id uuid primary key default gen_random_uuid(), storage_key text unique, public_url text, content_type text,
 byte_size bigint check(byte_size is null or byte_size >= 0), width integer, height integer, alt_text text,
 metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.articles (
 id bigint generated by default as identity primary key,
 status text not null default 'draft' check(status in ('draft','published','archived')),
 title text not null, alias text not null unique, category_id bigint references public.article_categories(id) on delete restrict,
 tournament_id bigint references public.tournaments(id) on delete restrict,
 published_at timestamptz, intro_html text not null default '', body_html text not null default '',
 featured boolean not null default false, logo_media_id uuid references public.media_assets(id) on delete set null,
 video_url text, seo_title text, seo_description text, legacy_article_id bigint unique,
 created_by uuid references public.profiles(id), updated_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 check (btrim(title) <> '' and alias ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
 check (category_id is not null or tournament_id is not null),
 check (status <> 'published' or published_at is not null)
);
create table if not exists public.article_profiles (
 article_id bigint not null references public.articles(id) on delete cascade, profile_id uuid not null references public.profiles(id) on delete restrict,
 primary key(article_id, profile_id)
);
create index if not exists articles_public_idx on public.articles(status,published_at desc);
create index if not exists articles_category_idx on public.articles(category_id);

-- Preserve the existing 383 public snapshot without granting it authority over operational fields.
-- Legacy imports predate category/tournament association; attach a private migration category.
insert into public.article_categories(status,title,alias,description) values(true,'Imported news','imported-news','Legacy public article mapping') on conflict(alias) do nothing;
insert into public.articles(legacy_article_id,status,title,alias,category_id,published_at,intro_html,body_html,featured,video_url,seo_title,created_at,updated_at)
select legacy_id,'published',title,coalesce(nullif(alias,''),'legacy-'||legacy_id),(select id from public.article_categories where alias='imported-news'),published_at,coalesce(excerpt,''),coalesce(excerpt,''),false,video_url,title,created_at,updated_at
from public.dpt_public_articles
where legacy_id is not null
on conflict (legacy_article_id) do nothing;


create table if not exists public.notification_campaigns (
 id uuid primary key default gen_random_uuid(), idempotency_key uuid not null unique,
 title text not null, message_html text not null, email_enabled boolean not null default false, sms_enabled boolean not null default false,
 sms_body text, target jsonb not null default '{}'::jsonb, sender_profile_id uuid not null references public.profiles(id),
 status text not null default 'queued' check(status in ('queued','dry_run','cancelled')),
 created_at timestamptz not null default now(), check(btrim(title)<>'' and btrim(message_html)<>''),
 check((not sms_enabled) or nullif(btrim(coalesce(sms_body,'')),'') is not null)
);
create table if not exists public.notification_recipients (
 campaign_id uuid not null references public.notification_campaigns(id) on delete cascade, profile_id uuid not null references public.profiles(id) on delete restrict,
 recipient_snapshot jsonb not null, channels text[] not null default '{}'::text[], created_at timestamptz not null default now(), primary key(campaign_id,profile_id)
);
create table if not exists public.notification_deliveries (
 id uuid primary key default gen_random_uuid(), campaign_id uuid not null references public.notification_campaigns(id) on delete cascade,
 profile_id uuid not null references public.profiles(id) on delete restrict, channel text not null check(channel in ('email','sms','internal')),
 status text not null default 'suppressed' check(status in ('queued','suppressed','sent','failed')), provider_message_id text, created_at timestamptz not null default now(), sent_at timestamptz,
 unique(campaign_id,profile_id,channel)
);
create table if not exists public.internal_notifications (
 id uuid primary key default gen_random_uuid(), campaign_id uuid references public.notification_campaigns(id) on delete set null,
 profile_id uuid not null references public.profiles(id) on delete cascade, title text not null, message_html text not null,
 read_at timestamptz, created_at timestamptz not null default now(), unique(campaign_id,profile_id)
);

create table if not exists public.email_templates (
 id uuid primary key default gen_random_uuid(), title text not null, subject text not null, body_html text not null,
 status text not null default 'draft' check(status in ('draft','published','archived')), template_type text not null default 'user' check(template_type in ('system','user')),
 allowed_variables text[] not null default '{}', created_by uuid references public.profiles(id), updated_by uuid references public.profiles(id),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(title)
);
create table if not exists public.email_template_versions (
 id uuid primary key default gen_random_uuid(), template_id uuid not null references public.email_templates(id) on delete cascade,
 version integer not null, snapshot jsonb not null, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), unique(template_id,version)
);
create table if not exists public.email_template_attachments (
 id uuid primary key default gen_random_uuid(), template_id uuid not null references public.email_templates(id) on delete cascade,
 media_id uuid references public.media_assets(id) on delete restrict, filename text not null, content_type text, byte_size bigint check(byte_size is null or byte_size>=0), metadata jsonb not null default '{}'::jsonb
);

-- The public surface is a security-invoker view, not the operational table.
create or replace view public.dpt_public_published_articles with (security_invoker=true) as
select a.id,a.alias,a.title,a.intro_html as excerpt,a.published_at,a.video_url,a.featured,
 t.alias as tournament_alias, a.legacy_article_id
from public.articles a left join public.dpt_public_tournaments t on t.legacy_id=a.tournament_id
where a.status='published' and a.published_at <= now();

alter table public.article_categories enable row level security; alter table public.articles enable row level security; alter table public.article_profiles enable row level security; alter table public.media_assets enable row level security;
alter table public.notification_campaigns enable row level security; alter table public.notification_recipients enable row level security; alter table public.notification_deliveries enable row level security; alter table public.internal_notifications enable row level security;
alter table public.email_templates enable row level security; alter table public.email_template_versions enable row level security; alter table public.email_template_attachments enable row level security;
create policy "content categories operators" on public.article_categories for select to authenticated using(private.has_permission('manage_categories'));
create policy "content articles operators" on public.articles for select to authenticated using(private.has_permission('manage_articles'));
create policy "public published articles" on public.articles for select to anon,authenticated using(status='published' and published_at<=now());
create policy "article profiles operators" on public.article_profiles for select to authenticated using(private.has_permission('manage_articles'));
create policy "media operators" on public.media_assets for select to authenticated using(private.has_permission('manage_articles') or private.has_permission('manage_email_templates'));
create policy "campaigns operators" on public.notification_campaigns for select to authenticated using(private.has_permission('manage_notifications'));
create policy "campaign recipients operators" on public.notification_recipients for select to authenticated using(private.has_permission('manage_notifications'));
create policy "campaign deliveries operators" on public.notification_deliveries for select to authenticated using(private.has_permission('manage_notifications'));
create policy "internal inbox owner or operators" on public.internal_notifications for select to authenticated using(profile_id=(select id from public.profiles where auth_user_id=auth.uid() limit 1) or private.has_permission('read_internal_notifications'));
create policy "templates operators" on public.email_templates for select to authenticated using(private.has_permission('manage_email_templates'));
create policy "template versions operators" on public.email_template_versions for select to authenticated using(private.has_permission('manage_email_templates'));
create policy "template attachments operators" on public.email_template_attachments for select to authenticated using(private.has_permission('manage_email_templates'));
revoke all on public.article_categories,public.articles,public.article_profiles,public.media_assets,public.notification_campaigns,public.notification_recipients,public.notification_deliveries,public.internal_notifications,public.email_templates,public.email_template_versions,public.email_template_attachments from anon;
grant select(id,alias,title,intro_html,published_at,video_url,featured,tournament_id,legacy_article_id,status) on public.articles to anon;
grant select on public.dpt_public_published_articles to anon,authenticated;
grant select on public.article_categories,public.articles,public.article_profiles,public.media_assets,public.notification_campaigns,public.notification_recipients,public.notification_deliveries,public.internal_notifications,public.email_templates,public.email_template_versions,public.email_template_attachments to authenticated;

create or replace function private.dpt_actor() returns uuid language sql stable security definer set search_path=pg_catalog,public,private as $$ select id from public.profiles where auth_user_id=auth.uid() and deleted_at is null limit 1 $$;
create or replace function private.sanitize_html(p_html text) returns text language sql immutable set search_path=pg_catalog as $$
 select regexp_replace(regexp_replace(regexp_replace(coalesce(p_html,''),'<(script|style|iframe)[^>]*>.*?</\1>','','gis'),'\son[a-z]+\s*=\s*(["'']).*?\1','','gis'),'javascript:','','gi') $$;
create or replace function private.require_content_object(p jsonb) returns void language plpgsql immutable as $$ begin if jsonb_typeof(p)<>'object' then raise exception 'object payload required' using errcode='22023'; end if; end $$;

create or replace function public.dpt_admin_save_category(p_id bigint,p_values jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare actor uuid:=private.dpt_actor(); before_data jsonb; result jsonb; v_alias text;
begin if not private.has_permission('manage_categories') or actor is null then raise exception 'permission denied' using errcode='42501'; end if; perform private.require_content_object(p_values); v_alias:=lower(trim(both '-' from regexp_replace(coalesce(p_values->>'alias',p_values->>'title',''),'[^a-zA-Z0-9]+','-','g'))); if nullif(btrim(p_values->>'title'),'') is null or v_alias='' then raise exception 'title required' using errcode='22023'; end if;
 if p_id is null then insert into public.article_categories(status,title,alias,parent_id,description,seo_title,seo_description) values(coalesce((p_values->>'status')::boolean,true),btrim(p_values->>'title'),v_alias,nullif(p_values->>'parent_id','')::bigint,nullif(btrim(p_values->>'description'),''),nullif(btrim(p_values->>'seo_title'),''),nullif(btrim(p_values->>'seo_description'),'')) returning to_jsonb(article_categories.*) into result;
 else select to_jsonb(c.*) into before_data from public.article_categories c where id=p_id for update; if before_data is null or p_id=nullif(p_values->>'parent_id','')::bigint then raise exception 'invalid category' using errcode='22023'; end if; update public.article_categories set status=coalesce((p_values->>'status')::boolean,status),title=btrim(p_values->>'title'),alias=v_alias,parent_id=nullif(p_values->>'parent_id','')::bigint,description=nullif(btrim(p_values->>'description'),''),seo_title=nullif(btrim(p_values->>'seo_title'),''),seo_description=nullif(btrim(p_values->>'seo_description'),''),updated_at=now() where id=p_id returning to_jsonb(article_categories.*) into result; end if;
 insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),actor,case when p_id is null then 'create' else 'update' end,'article_category',(result->>'id'),before_data,result); return result; end $$;
create or replace function public.dpt_admin_delete_category(p_id bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare actor uuid:=private.dpt_actor(); before_data jsonb; begin if not private.has_permission('manage_categories') or actor is null then raise exception 'permission denied' using errcode='42501'; end if; select to_jsonb(c.*) into before_data from public.article_categories c where id=p_id for update; if before_data is null then raise exception 'category not found'; end if; if exists(select 1 from public.articles where category_id=p_id) or exists(select 1 from public.article_categories where parent_id=p_id) then raise exception 'referenced category cannot be deleted' using errcode='23503'; end if; delete from public.article_categories where id=p_id; insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,before_data) values(auth.uid(),actor,'delete','article_category',p_id::text,before_data); return before_data; end $$;
create or replace function public.dpt_admin_save_article(p_id bigint,p_values jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare actor uuid:=private.dpt_actor(); before_data jsonb; result jsonb; v_alias text; begin if not private.has_permission('manage_articles') or actor is null then raise exception 'permission denied' using errcode='42501'; end if; perform private.require_content_object(p_values); v_alias:=lower(trim(both '-' from regexp_replace(coalesce(p_values->>'alias',p_values->>'title',''),'[^a-zA-Z0-9]+','-','g'))); if nullif(btrim(p_values->>'title'),'') is null or v_alias='' or (p_values->>'category_id' is null and p_values->>'tournament_id' is null) then raise exception 'title and category or tournament required' using errcode='22023'; end if; if p_id is null then insert into public.articles(status,title,alias,category_id,tournament_id,published_at,intro_html,body_html,featured,video_url,seo_title,seo_description,created_by,updated_by) values(coalesce(nullif(p_values->>'status',''),'draft'),btrim(p_values->>'title'),v_alias,nullif(p_values->>'category_id','')::bigint,nullif(p_values->>'tournament_id','')::bigint,nullif(p_values->>'published_at','')::timestamptz,private.sanitize_html(p_values->>'intro_html'),private.sanitize_html(p_values->>'body_html'),coalesce((p_values->>'featured')::boolean,false),nullif(btrim(p_values->>'video_url'),''),nullif(btrim(p_values->>'seo_title'),''),nullif(btrim(p_values->>'seo_description'),''),actor,actor) returning to_jsonb(articles.*) into result; else select to_jsonb(a.*) into before_data from public.articles a where id=p_id for update; if before_data is null then raise exception 'article not found'; end if; update public.articles set status=coalesce(nullif(p_values->>'status',''),status),title=btrim(p_values->>'title'),alias=v_alias,category_id=nullif(p_values->>'category_id','')::bigint,tournament_id=nullif(p_values->>'tournament_id','')::bigint,published_at=nullif(p_values->>'published_at','')::timestamptz,intro_html=private.sanitize_html(p_values->>'intro_html'),body_html=private.sanitize_html(p_values->>'body_html'),featured=coalesce((p_values->>'featured')::boolean,false),video_url=nullif(btrim(p_values->>'video_url'),''),seo_title=nullif(btrim(p_values->>'seo_title'),''),seo_description=nullif(btrim(p_values->>'seo_description'),''),updated_by=actor,updated_at=now() where id=p_id returning to_jsonb(articles.*) into result; end if; delete from public.article_profiles where article_id=(result->>'id')::bigint; insert into public.article_profiles(article_id,profile_id) select (result->>'id')::bigint,value::uuid from jsonb_array_elements_text(coalesce(p_values->'profile_ids','[]'::jsonb)) value join public.profiles profile on profile.id=value::uuid and profile.deleted_at is null on conflict do nothing; insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),actor,case when p_id is null then 'create' else 'update' end,'article',result->>'id',before_data,result); return result; end $$;
create or replace function public.dpt_admin_delete_article(p_id bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare actor uuid:=private.dpt_actor(); before_data jsonb; begin if not private.has_permission('manage_articles') or actor is null then raise exception 'permission denied' using errcode='42501'; end if; select to_jsonb(a.*) into before_data from public.articles a where id=p_id for update; if before_data is null then raise exception 'article not found'; end if; delete from public.articles where id=p_id; insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,before_data) values(auth.uid(),actor,'delete','article',p_id::text,before_data); return before_data; end $$;

create or replace function public.dpt_admin_create_notification(p_values jsonb,p_idempotency uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare actor uuid:=private.dpt_actor(); campaign uuid; existing jsonb; target_ids uuid[]; target jsonb:=coalesce(p_values->'target','{}'::jsonb); dry_run boolean:=coalesce((p_values->>'dry_run')::boolean,false); recipient_count integer;
begin
 if not private.has_permission('manage_notifications') or actor is null then raise exception 'permission denied' using errcode='42501'; end if;
 perform private.require_content_object(p_values);
 if nullif(btrim(p_values->>'title'),'') is null or nullif(btrim(p_values->>'message_html'),'') is null then raise exception 'title and message required' using errcode='22023'; end if;
 if coalesce((p_values->>'sms_enabled')::boolean,false) and nullif(btrim(p_values->>'sms_body'),'') is null then raise exception 'SMS body required' using errcode='22023'; end if;
 if coalesce(jsonb_array_length(coalesce(p_values->'profile_ids','[]'::jsonb)),0)=0 and coalesce(jsonb_array_length(coalesce(target->'venue_ids','[]'::jsonb)),0)=0 and coalesce(jsonb_array_length(coalesce(target->'season_ids','[]'::jsonb)),0)=0 and coalesce(jsonb_array_length(coalesce(target->'event_ids','[]'::jsonb)),0)=0 and coalesce(jsonb_array_length(coalesce(target->'league_ids','[]'::jsonb)),0)=0 and coalesce(jsonb_array_length(coalesce(target->'tournament_ids','[]'::jsonb)),0)=0 and coalesce(jsonb_array_length(coalesce(target->'role_names','[]'::jsonb)),0)=0 then raise exception 'at least one target is required' using errcode='22023'; end if;
 with candidates as (
  select distinct profile.id from public.profiles profile where profile.deleted_at is null and profile.merged_into is null and profile.status='active' and (
   (coalesce(jsonb_array_length(coalesce(p_values->'profile_ids','[]'::jsonb)),0)>0 and profile.id in(select value::uuid from jsonb_array_elements_text(p_values->'profile_ids') value))
   or (coalesce(jsonb_array_length(coalesce(p_values->'profile_ids','[]'::jsonb)),0)=0
    and (coalesce(jsonb_array_length(coalesce(target->'venue_ids','[]'::jsonb)),0)=0 or exists(select 1 from public.tournament_entries entry join public.tournaments tournament on tournament.id=entry.tournament_id where entry.player_id=profile.id and tournament.venue_id in(select value::bigint from jsonb_array_elements_text(target->'venue_ids') value)))
    and (coalesce(jsonb_array_length(coalesce(target->'season_ids','[]'::jsonb)),0)=0 or exists(select 1 from public.tournament_entries entry join public.tournaments tournament on tournament.id=entry.tournament_id join public.events event on event.id=tournament.event_id where entry.player_id=profile.id and event.season_id in(select value::bigint from jsonb_array_elements_text(target->'season_ids') value)))
    and (coalesce(jsonb_array_length(coalesce(target->'event_ids','[]'::jsonb)),0)=0 or exists(select 1 from public.tournament_entries entry join public.tournaments tournament on tournament.id=entry.tournament_id where entry.player_id=profile.id and tournament.event_id in(select value::bigint from jsonb_array_elements_text(target->'event_ids') value)))
    and (coalesce(jsonb_array_length(coalesce(target->'league_ids','[]'::jsonb)),0)=0 or exists(select 1 from public.tournament_entries entry join public.tournaments tournament on tournament.id=entry.tournament_id join public.events event on event.id=tournament.event_id join public.seasons season on season.id=event.season_id where entry.player_id=profile.id and season.league_id in(select value::bigint from jsonb_array_elements_text(target->'league_ids') value)))
    and (coalesce(jsonb_array_length(coalesce(target->'tournament_ids','[]'::jsonb)),0)=0 or exists(select 1 from public.tournament_entries entry where entry.player_id=profile.id and entry.tournament_id in(select value::bigint from jsonb_array_elements_text(target->'tournament_ids') value)))
    and (coalesce(jsonb_array_length(coalesce(target->'role_names','[]'::jsonb)),0)=0 or exists(select 1 from public.profile_roles role where role.profile_id=profile.id and role.role::text in(select value from jsonb_array_elements_text(target->'role_names') value)))
   )
  )
 ), including_sender as (select id from candidates union select actor)
 select array_agg(id order by id) into target_ids from including_sender;
 recipient_count:=coalesce(cardinality(target_ids),0);
 if dry_run then return jsonb_build_object('status','preview','recipients',recipient_count,'external_delivery',false); end if;
 select jsonb_build_object('id',id,'status',status,'recipients',(select count(*) from public.notification_recipients where campaign_id=notification_campaigns.id)) into existing from public.notification_campaigns where idempotency_key=p_idempotency;
 if existing is not null then return existing; end if;
 insert into public.notification_campaigns(idempotency_key,title,message_html,email_enabled,sms_enabled,sms_body,target,sender_profile_id,status) values(p_idempotency,btrim(p_values->>'title'),private.sanitize_html(p_values->>'message_html'),coalesce((p_values->>'email_enabled')::boolean,false),coalesce((p_values->>'sms_enabled')::boolean,false),nullif(btrim(p_values->>'sms_body'),''),target,actor,'queued') returning id into campaign;
 insert into public.notification_recipients(campaign_id,profile_id,recipient_snapshot,channels) select campaign,profile.id,jsonb_build_object('id',profile.id,'name',concat_ws(' ',profile.first_name,profile.last_name)),array_remove(array['internal',case when coalesce((p_values->>'email_enabled')::boolean,false) and profile.email is not null and coalesce((profile.legacy_data->>'verified_email')::boolean,false) and coalesce(pref.email_enabled,true) then 'email' end,case when coalesce((p_values->>'sms_enabled')::boolean,false) and profile.mobile is not null and coalesce((profile.legacy_data->>'verified_phone')::boolean,false) and coalesce(pref.sms_enabled,false) then 'sms' end],null) from public.profiles profile left join public.profile_notification_preferences pref on pref.profile_id=profile.id where profile.id=any(coalesce(target_ids,array[]::uuid[]));
 insert into public.internal_notifications(campaign_id,profile_id,title,message_html) select campaign,recipient.profile_id,btrim(p_values->>'title'),private.sanitize_html(p_values->>'message_html') from public.notification_recipients recipient where recipient.campaign_id=campaign;
 insert into public.notification_deliveries(campaign_id,profile_id,channel,status,sent_at) select campaign,recipient.profile_id,channel,case when channel='internal' then 'sent' else 'suppressed' end,case when channel='internal' then now() end from public.notification_recipients recipient cross join lateral unnest(recipient.channels) channel where recipient.campaign_id=campaign;
 insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,after_data) values(auth.uid(),actor,'create','notification_campaign',campaign::text,jsonb_build_object('status','queued','recipients',recipient_count,'external_delivery',false));
 return jsonb_build_object('id',campaign,'status','queued','recipients',recipient_count,'external_delivery',false);
end $$;
create or replace function public.dpt_admin_mark_internal_notification_read(p_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare actor uuid:=private.dpt_actor(); result jsonb; begin if actor is null then raise exception 'permission denied' using errcode='42501'; end if; update public.internal_notifications set read_at=coalesce(read_at,now()) where id=p_id and profile_id=actor returning to_jsonb(internal_notifications.*) into result; if result is null then raise exception 'notification not found' using errcode='42501'; end if; return result; end $$;
create or replace function public.dpt_admin_save_email_template(p_id uuid,p_values jsonb) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare actor uuid:=private.dpt_actor(); result jsonb; next_version integer; before_data jsonb; begin if not private.has_permission('manage_email_templates') or actor is null then raise exception 'permission denied' using errcode='42501'; end if; perform private.require_content_object(p_values); if nullif(btrim(p_values->>'title'),'') is null or nullif(btrim(p_values->>'subject'),'') is null then raise exception 'title and subject required' using errcode='22023'; end if; if p_id is null then insert into public.email_templates(title,subject,body_html,status,template_type,allowed_variables,created_by,updated_by) values(btrim(p_values->>'title'),btrim(p_values->>'subject'),private.sanitize_html(p_values->>'body_html'),coalesce(nullif(p_values->>'status',''),'draft'),coalesce(nullif(p_values->>'template_type',''),'user'),coalesce(array(select jsonb_array_elements_text(p_values->'allowed_variables')),'{}'),actor,actor) returning to_jsonb(email_templates.*) into result; else select to_jsonb(t.*) into before_data from public.email_templates t where id=p_id for update; if before_data is null then raise exception 'template not found'; end if; update public.email_templates set title=btrim(p_values->>'title'),subject=btrim(p_values->>'subject'),body_html=private.sanitize_html(p_values->>'body_html'),status=coalesce(nullif(p_values->>'status',''),status),allowed_variables=coalesce(array(select jsonb_array_elements_text(p_values->'allowed_variables')),allowed_variables),updated_by=actor,updated_at=now() where id=p_id returning to_jsonb(email_templates.*) into result; end if; select coalesce(max(version),0)+1 into next_version from public.email_template_versions where template_id=(result->>'id')::uuid; insert into public.email_template_versions(template_id,version,snapshot,created_by) values((result->>'id')::uuid,next_version,result,actor); insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),actor,case when p_id is null then 'create' else 'update' end,'email_template',result->>'id',before_data,result); return result||jsonb_build_object('version',next_version); end $$;
create or replace function public.dpt_admin_copy_email_template(p_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare source public.email_templates%rowtype; begin if not private.has_permission('manage_email_templates') then raise exception 'permission denied' using errcode='42501'; end if; select * into source from public.email_templates where id=p_id; if not found then raise exception 'template not found'; end if; return public.dpt_admin_save_email_template(null,jsonb_build_object('title',source.title||' (Copy)','subject',source.subject,'body_html',source.body_html,'status','draft','template_type','user','allowed_variables',to_jsonb(source.allowed_variables))); end $$;
create or replace function public.dpt_admin_archive_email_template(p_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare actor uuid:=private.dpt_actor(); before_data jsonb; result jsonb; begin if not private.has_permission('manage_email_templates') or actor is null then raise exception 'permission denied' using errcode='42501'; end if; select to_jsonb(template.*) into before_data from public.email_templates template where id=p_id for update; if before_data is null then raise exception 'template not found'; end if; if before_data->>'template_type'='system' then raise exception 'system template is protected' using errcode='42501'; end if; update public.email_templates set status='archived',updated_by=actor,updated_at=now() where id=p_id returning to_jsonb(email_templates.*) into result; insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),actor,'archive','email_template',p_id::text,before_data,result); return result; end $$;
revoke all on function public.dpt_admin_save_category(bigint,jsonb),public.dpt_admin_delete_category(bigint),public.dpt_admin_save_article(bigint,jsonb),public.dpt_admin_delete_article(bigint),public.dpt_admin_create_notification(jsonb,uuid),public.dpt_admin_mark_internal_notification_read(uuid),public.dpt_admin_save_email_template(uuid,jsonb),public.dpt_admin_copy_email_template(uuid),public.dpt_admin_archive_email_template(uuid) from public,anon;
grant execute on function public.dpt_admin_save_category(bigint,jsonb),public.dpt_admin_delete_category(bigint),public.dpt_admin_save_article(bigint,jsonb),public.dpt_admin_delete_article(bigint),public.dpt_admin_create_notification(jsonb,uuid),public.dpt_admin_mark_internal_notification_read(uuid),public.dpt_admin_save_email_template(uuid,jsonb),public.dpt_admin_copy_email_template(uuid),public.dpt_admin_archive_email_template(uuid) to authenticated;
commit;
