begin;

-- Production tournament setup fields kept outside opaque importer/legacy JSON.
alter table public.tournaments
  add column if not exists featured boolean not null default false,
  add column if not exists multi_day boolean not null default false,
  add column if not exists logo_url text,
  add column if not exists banner_url text,
  add column if not exists live_stream_url text,
  add column if not exists point_distribution_id bigint references public.payout_templates(id),
  add column if not exists qualifier_tournament boolean not null default false,
  add column if not exists advancing_to_flight_tournaments boolean not null default false,
  add column if not exists allowed_rebuys_limit integer,
  add column if not exists allow_rebuy_chips boolean not null default false,
  add column if not exists title_count boolean not null default false,
  add column if not exists blind_intervals integer;

update public.tournaments set
 featured=coalesce(nullif(legacy_data->>'featured','')::boolean,featured),
 multi_day=coalesce(nullif(legacy_data->>'multi_day','')::boolean,multi_day),
 logo_url=coalesce(logo_url,legacy_data->>'logo'), banner_url=coalesce(banner_url,legacy_data->>'banner_image'),
 live_stream_url=coalesce(live_stream_url,legacy_data->>'live_stream_url'),
 point_distribution_id=coalesce((select template.id from public.payout_templates template where template.id=nullif(legacy_data->>'point_distribution_id','')::bigint and template.deleted_at is null),point_distribution_id),
 qualifier_tournament=coalesce(nullif(legacy_data->>'qualifier_tournament','')::boolean,qualifier_tournament),
 advancing_to_flight_tournaments=coalesce(nullif(legacy_data->>'advancing_to_flight_tournaments','')::boolean,advancing_to_flight_tournaments),
 allowed_rebuys_limit=coalesce(allowed_rebuys_limit,nullif(legacy_data->>'allowed_rebuys_limit','')::integer),
 allow_rebuy_chips=coalesce(nullif(legacy_data->>'allow_rebuy_chips','')::boolean,allow_rebuy_chips),
 title_count=coalesce(nullif(legacy_data->>'title_count','')::boolean,title_count),
 blind_intervals=coalesce(blind_intervals,nullif(legacy_data->>'blind_intervals','')::integer);

create or replace function public.dpt_admin_save_tournament(p_id bigint, p_values jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare before_row jsonb; result jsonb; actor uuid; new_id bigint; v_event bigint; v_venue bigint; v_type bigint; v_blind bigint; v_payout bigint; v_point bigint;
begin
 if auth.uid() is null or not private.is_admin_operator() then raise exception 'DPT administrator authorization required' using errcode='42501'; end if;
 if jsonb_typeof(p_values)<>'object' or nullif(btrim(coalesce(p_values->>'name','')),'') is null then raise exception 'Tournament name is required' using errcode='22023'; end if;
 perform pg_advisory_xact_lock(hashtext('dpt-tournament:'||coalesce(p_id,0)::text));
 select id into actor from profiles where auth_user_id=auth.uid() and status='active' and deleted_at is null limit 1; if actor is null then raise exception 'Active operator profile required' using errcode='42501'; end if;
 v_event:=nullif(p_values->>'event_id','')::bigint; v_venue:=nullif(p_values->>'venue_id','')::bigint; v_type:=nullif(p_values->>'tournament_type_id','')::bigint; v_blind:=nullif(p_values->>'blind_structure_id','')::bigint; v_payout:=nullif(p_values->>'payout_template_id','')::bigint; v_point:=nullif(p_values->>'point_distribution_id','')::bigint;
 if v_event is not null and not exists(select 1 from events where id=v_event and status and deleted_at is null) then raise exception 'Event must be active' using errcode='23503'; end if;
 if v_venue is not null and not exists(select 1 from venues where id=v_venue and status and deleted_at is null) then raise exception 'Venue must be active' using errcode='23503'; end if;
 if v_type is null or not exists(select 1 from tournament_types where id=v_type) then raise exception 'Tournament type is required' using errcode='23503'; end if;
 if v_blind is not null and not exists(select 1 from blind_structures where id=v_blind and status and deleted_at is null) then raise exception 'Blind structure must be active' using errcode='23503'; end if;
 if v_payout is not null and not exists(select 1 from payout_templates where id=v_payout and deleted_at is null) then raise exception 'Payout template not found' using errcode='23503'; end if;
 if v_point is not null and not exists(select 1 from payout_templates where id=v_point and deleted_at is null) then raise exception 'Point distribution not found' using errcode='23503'; end if;
 if nullif(p_values->>'starts_at','') is not null and nullif(p_values->>'ends_at','') is not null and (p_values->>'ends_at')::timestamptz < (p_values->>'starts_at')::timestamptz then raise exception 'End date must not precede start date' using errcode='22023'; end if;
 if nullif(p_values->>'registration_starts_at','') is not null and nullif(p_values->>'registration_ends_at','') is not null and (p_values->>'registration_ends_at')::timestamptz < (p_values->>'registration_starts_at')::timestamptz then raise exception 'Registration end must not precede start' using errcode='22023'; end if;
 if coalesce(nullif(p_values->>'minimum_buyin','')::integer,0)<0 or coalesce(nullif(p_values->>'dealer_fee','')::integer,0)<0 or coalesce(nullif(p_values->>'initial_chips_count','')::integer,0)<0 or coalesce(nullif(p_values->>'allowed_rebuys_limit','')::integer,0)<0 or coalesce(nullif(p_values->>'blind_intervals','')::integer,1)<=0 then raise exception 'Fees, chips, rebuy limits and intervals must be valid' using errcode='22023'; end if;
 if p_id is not null then select to_jsonb(t) into before_row from tournaments t where id=p_id and deleted_at is null for update; if before_row is null then raise exception 'Tournament not found'; end if; end if;
 if p_id is null then
  insert into tournaments(event_id,venue_id,tournament_type_id,blind_structure_id,payout_template_id,name,alias,short_description,long_description,rules_description,starts_at,ends_at,registration_starts_at,registration_ends_at,dealer_fee,tournament_fee_percent,minimum_buyin,maximum_buyin,allow_rebuy,rebuy_amount,rebuy_fee,rebuy_chips_count,initial_chips_count,players_at_final_table,points_multiplier_enabled,points_multiplier_value,participation_bonus_points,chip_carryover,allow_search_registration,status,featured,multi_day,logo_url,live_stream_url,banner_url,qualifier_tournament,advancing_to_flight_tournaments,legacy_data)
  values(v_event,v_venue,v_type,v_blind,v_payout,trim(p_values->>'name'),coalesce(nullif(trim(p_values->>'alias'),''),trim(both '-' from regexp_replace(lower(trim(p_values->>'name')),'[^a-z0-9]+','-','g'))),nullif(p_values->>'short_description',''),nullif(p_values->>'long_description',''),nullif(p_values->>'rules_description',''),nullif(p_values->>'starts_at','')::timestamptz,nullif(p_values->>'ends_at','')::timestamptz,nullif(p_values->>'registration_starts_at','')::timestamptz,nullif(p_values->>'registration_ends_at','')::timestamptz,coalesce(nullif(p_values->>'dealer_fee','')::integer,0),coalesce(nullif(p_values->>'tournament_fee_percent','')::numeric,0),coalesce(nullif(p_values->>'minimum_buyin','')::integer,0),nullif(p_values->>'maximum_buyin','')::integer,coalesce(nullif(p_values->>'allow_rebuy','')::boolean,false),coalesce(nullif(p_values->>'rebuy_amount','')::integer,0),coalesce(nullif(p_values->>'rebuy_fee','')::integer,0),coalesce(nullif(p_values->>'rebuy_chips_count','')::integer,0),coalesce(nullif(p_values->>'initial_chips_count','')::integer,0),nullif(p_values->>'players_at_final_table','')::integer,coalesce(nullif(p_values->>'points_multiplier_enabled','')::boolean,false),nullif(p_values->>'points_multiplier_value','')::numeric,coalesce(nullif(p_values->>'participation_bonus_points','')::integer,0),nullif(p_values->>'chip_carryover','')::chip_carryover_mode,coalesce(nullif(p_values->>'allow_search_registration','')::boolean,true),coalesce(nullif(p_values->>'status','')::boolean,false),coalesce(nullif(p_values->>'featured','')::boolean,false),coalesce(nullif(p_values->>'multi_day','')::boolean,false),nullif(p_values->>'logo_url',''),nullif(p_values->>'live_stream_url',''),nullif(p_values->>'banner_url',''),coalesce(nullif(p_values->>'qualifier_tournament','')::boolean,false),coalesce(nullif(p_values->>'advancing_to_flight_tournaments','')::boolean,false),coalesce(p_values->'legacy_data','{}'::jsonb)) returning id,to_jsonb(tournaments.*) into new_id,result;
 else
  update tournaments set event_id=v_event,venue_id=v_venue,tournament_type_id=v_type,blind_structure_id=v_blind,payout_template_id=v_payout,name=trim(p_values->>'name'),short_description=nullif(p_values->>'short_description',''),long_description=nullif(p_values->>'long_description',''),rules_description=nullif(p_values->>'rules_description',''),starts_at=nullif(p_values->>'starts_at','')::timestamptz,ends_at=nullif(p_values->>'ends_at','')::timestamptz,registration_starts_at=nullif(p_values->>'registration_starts_at','')::timestamptz,registration_ends_at=nullif(p_values->>'registration_ends_at','')::timestamptz,dealer_fee=coalesce(nullif(p_values->>'dealer_fee','')::integer,0),tournament_fee_percent=coalesce(nullif(p_values->>'tournament_fee_percent','')::numeric,0),minimum_buyin=coalesce(nullif(p_values->>'minimum_buyin','')::integer,0),maximum_buyin=nullif(p_values->>'maximum_buyin','')::integer,allow_rebuy=coalesce(nullif(p_values->>'allow_rebuy','')::boolean,false),rebuy_amount=coalesce(nullif(p_values->>'rebuy_amount','')::integer,0),rebuy_fee=coalesce(nullif(p_values->>'rebuy_fee','')::integer,0),rebuy_chips_count=coalesce(nullif(p_values->>'rebuy_chips_count','')::integer,0),initial_chips_count=coalesce(nullif(p_values->>'initial_chips_count','')::integer,0),players_at_final_table=nullif(p_values->>'players_at_final_table','')::integer,points_multiplier_enabled=coalesce(nullif(p_values->>'points_multiplier_enabled','')::boolean,false),points_multiplier_value=nullif(p_values->>'points_multiplier_value','')::numeric,participation_bonus_points=coalesce(nullif(p_values->>'participation_bonus_points','')::integer,0),chip_carryover=nullif(p_values->>'chip_carryover','')::chip_carryover_mode,allow_search_registration=coalesce(nullif(p_values->>'allow_search_registration','')::boolean,true),status=coalesce(nullif(p_values->>'status','')::boolean,status),featured=coalesce(nullif(p_values->>'featured','')::boolean,false),multi_day=coalesce(nullif(p_values->>'multi_day','')::boolean,false),logo_url=nullif(p_values->>'logo_url',''),live_stream_url=nullif(p_values->>'live_stream_url',''),banner_url=nullif(p_values->>'banner_url',''),qualifier_tournament=coalesce(nullif(p_values->>'qualifier_tournament','')::boolean,false),advancing_to_flight_tournaments=coalesce(nullif(p_values->>'advancing_to_flight_tournaments','')::boolean,false),legacy_data=coalesce(p_values->'legacy_data',legacy_data),updated_at=now() where id=p_id returning to_jsonb(tournaments.*) into result;
 end if;
 update tournaments set
  point_distribution_id=v_point,
  allowed_rebuys_limit=nullif(p_values->>'allowed_rebuys_limit','')::integer,
  allow_rebuy_chips=coalesce(nullif(p_values->>'allow_rebuy_chips','')::boolean,false),
  title_count=coalesce(nullif(p_values->>'title_count','')::boolean,false),
  blind_intervals=nullif(p_values->>'blind_intervals','')::integer
 where id=coalesce(p_id,new_id) returning to_jsonb(tournaments.*) into result;
 insert into dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,tournament_id,before_data,after_data) values(auth.uid(),actor,case when p_id is null then 'create' else 'update' end,'tournament',coalesce(p_id,new_id)::text,coalesce(p_id,new_id),before_row,result); return result;
end $$;

create or replace function public.dpt_admin_copy_tournament(p_id bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare actor uuid; source public.tournaments%rowtype; result jsonb; new_id bigint;
begin
 if auth.uid() is null or not private.is_admin_operator() then raise exception 'DPT administrator authorization required' using errcode='42501'; end if; perform pg_advisory_xact_lock(hashtext('dpt-tournament:'||p_id::text)); select id into actor from profiles where auth_user_id=auth.uid() and status='active' and deleted_at is null limit 1; if actor is null then raise exception 'Active operator profile required' using errcode='42501'; end if;
 select * into source from tournaments where id=p_id and deleted_at is null for update; if not found then raise exception 'Tournament not found'; end if;
 insert into tournaments(event_id,venue_id,tournament_type_id,blind_structure_id,payout_template_id,name,alias,short_description,long_description,rules_description,starts_at,ends_at,registration_starts_at,registration_ends_at,dealer_fee,tournament_fee_percent,minimum_buyin,maximum_buyin,allow_rebuy,rebuy_amount,rebuy_fee,rebuy_chips_count,initial_chips_count,players_at_final_table,points_multiplier_enabled,points_multiplier_value,participation_bonus_points,chip_carryover,allow_search_registration,status,featured,multi_day,logo_url,live_stream_url,banner_url,qualifier_tournament,advancing_to_flight_tournaments,legacy_data) select event_id,venue_id,tournament_type_id,blind_structure_id,payout_template_id,name||' Copy',null,short_description,long_description,rules_description,starts_at,ends_at,registration_starts_at,registration_ends_at,dealer_fee,tournament_fee_percent,minimum_buyin,maximum_buyin,allow_rebuy,rebuy_amount,rebuy_fee,rebuy_chips_count,initial_chips_count,players_at_final_table,points_multiplier_enabled,points_multiplier_value,participation_bonus_points,chip_carryover,allow_search_registration,false,false,multi_day,logo_url,live_stream_url,banner_url,qualifier_tournament,advancing_to_flight_tournaments,legacy_data from tournaments where id=p_id returning id,to_jsonb(tournaments.*) into new_id,result;
 update tournaments set point_distribution_id=source.point_distribution_id,allowed_rebuys_limit=source.allowed_rebuys_limit,allow_rebuy_chips=source.allow_rebuy_chips,title_count=source.title_count,blind_intervals=source.blind_intervals where id=new_id returning to_jsonb(tournaments.*) into result;
 insert into dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,tournament_id,before_data,after_data) values(auth.uid(),actor,'copy','tournament',new_id::text,new_id,to_jsonb(source),result); return result;
end $$;

create or replace function public.dpt_admin_set_tournament_status(p_id bigint,p_status boolean) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare before_row jsonb; result jsonb; actor uuid; begin if auth.uid() is null or not private.is_admin_operator() then raise exception 'DPT administrator authorization required' using errcode='42501'; end if; perform pg_advisory_xact_lock(hashtext('dpt-tournament:'||p_id::text)); select id into actor from profiles where auth_user_id=auth.uid() and status='active' and deleted_at is null limit 1; select to_jsonb(t) into before_row from tournaments t where id=p_id and deleted_at is null for update; if before_row is null or actor is null then raise exception 'Tournament or active operator not found'; end if; update tournaments set status=p_status,updated_at=now() where id=p_id returning to_jsonb(tournaments.*) into result; insert into dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,tournament_id,before_data,after_data) values(auth.uid(),actor,'status','tournament',p_id::text,p_id,before_row,result); return result; end $$;
create or replace function public.dpt_admin_soft_delete_tournament(p_id bigint) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare before_row jsonb; result jsonb; actor uuid; begin if auth.uid() is null or not private.is_admin_operator() then raise exception 'DPT administrator authorization required' using errcode='42501'; end if; perform pg_advisory_xact_lock(hashtext('dpt-tournament:'||p_id::text)); select id into actor from profiles where auth_user_id=auth.uid() and status='active' and deleted_at is null limit 1; select to_jsonb(t) into before_row from tournaments t where id=p_id and deleted_at is null for update; if before_row is null or actor is null then raise exception 'Tournament or active operator not found'; end if; if (before_row->>'status')::boolean or exists(select 1 from tournament_entries where tournament_id=p_id and deleted_at is null) or exists(select 1 from tournament_entry_addons a join tournament_entries e on e.id=a.tournament_entry_id where e.tournament_id=p_id) or exists(select 1 from tournament_payouts where tournament_id=p_id) or exists(select 1 from tournament_updates where tournament_id=p_id and deleted_at is null) then raise exception 'Cannot delete active tournament or tournament with runtime data' using errcode='23503'; end if; update tournaments set deleted_at=now(),updated_at=now() where id=p_id returning to_jsonb(tournaments.*) into result; insert into dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,tournament_id,before_data,after_data) values(auth.uid(),actor,'soft_delete','tournament',p_id::text,p_id,before_row,result); return result; end $$;
revoke all on function public.dpt_admin_save_tournament(bigint,jsonb),public.dpt_admin_copy_tournament(bigint),public.dpt_admin_set_tournament_status(bigint,boolean),public.dpt_admin_soft_delete_tournament(bigint) from public,anon;
grant execute on function public.dpt_admin_save_tournament(bigint,jsonb),public.dpt_admin_copy_tournament(bigint),public.dpt_admin_set_tournament_status(bigint,boolean),public.dpt_admin_soft_delete_tournament(bigint) to authenticated;
commit;
