begin;

create table if not exists public.dpt_admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_auth_user_id uuid not null references auth.users(id),
  actor_profile_id uuid references public.profiles(id),
  action text not null,
  entity_type text not null,
  entity_id text not null,
  tournament_id bigint references public.tournaments(id) on delete set null,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

alter table public.dpt_admin_audit_log enable row level security;
revoke all on public.dpt_admin_audit_log from anon;
grant select on public.dpt_admin_audit_log to authenticated;

drop policy if exists "dpt admin audit readable by operators" on public.dpt_admin_audit_log;
create policy "dpt admin audit readable by operators"
  on public.dpt_admin_audit_log for select
  to authenticated
  using (private.is_admin_operator());

create or replace function public.dpt_admin_check_in_entry(
  p_tournament_id bigint,
  p_entry_id bigint,
  p_initial_buyin integer,
  p_initial_chips_count integer,
  p_total_buy_in_amount integer,
  p_no_of_addons integer,
  p_total_addon_chips integer,
  p_total_chips integer
)
returns public.tournament_entries
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  actor_profile_id uuid;
  before_entry public.tournament_entries;
  after_entry public.tournament_entries;
  audit_action text;
begin
  if auth.uid() is null or not private.is_admin_operator() then
    raise exception 'DPT administrator authorization required' using errcode = '42501';
  end if;

  select profile.id into actor_profile_id
  from public.profiles profile
  where profile.auth_user_id = auth.uid()
  limit 1;

  if actor_profile_id is null then
    raise exception 'Authenticated administrator profile is missing' using errcode = '42501';
  end if;

  if p_initial_buyin < 0
    or p_initial_chips_count < 0
    or p_total_buy_in_amount < 0
    or p_no_of_addons < 0
    or p_total_addon_chips < 0
    or p_total_chips < 0 then
    raise exception 'Tournament check-in totals cannot be negative' using errcode = '22023';
  end if;

  if p_total_chips <> p_initial_chips_count + p_total_addon_chips then
    raise exception 'Total chips must equal initial chips plus addon chips' using errcode = '22023';
  end if;

  if p_total_buy_in_amount < p_initial_buyin then
    raise exception 'Total buy-in cannot be less than initial buy-in' using errcode = '22023';
  end if;

  if p_no_of_addons = 0 and p_total_addon_chips <> 0 then
    raise exception 'Addon chips require at least one addon' using errcode = '22023';
  end if;

  select entry.* into before_entry
  from public.tournament_entries entry
  where entry.id = p_entry_id
    and entry.tournament_id = p_tournament_id
    and entry.deleted_at is null
  for update;

  if not found then
    raise exception 'Tournament entry was not found' using errcode = 'P0002';
  end if;

  audit_action := case
    when before_entry.checked_in then 'tournament_entry.edit_check_in'
    else 'tournament_entry.check_in'
  end;

  update public.tournament_entries entry
  set checked_in = true,
      checked_in_by = actor_profile_id,
      initial_buyin = p_initial_buyin,
      initial_chips_count = p_initial_chips_count,
      total_buy_in_amount = p_total_buy_in_amount,
      no_of_addons_buy = p_no_of_addons,
      total_addon_chips = p_total_addon_chips,
      total_chips = p_total_chips,
      updated_at = now()
  where entry.id = p_entry_id
  returning entry.* into after_entry;

  insert into public.dpt_admin_audit_log (
    actor_auth_user_id,
    actor_profile_id,
    action,
    entity_type,
    entity_id,
    tournament_id,
    before_data,
    after_data
  ) values (
    auth.uid(),
    actor_profile_id,
    audit_action,
    'tournament_entry',
    p_entry_id::text,
    p_tournament_id,
    to_jsonb(before_entry),
    to_jsonb(after_entry)
  );

  return after_entry;
end;
$$;

revoke all on function public.dpt_admin_check_in_entry(bigint,bigint,integer,integer,integer,integer,integer,integer) from public;
revoke all on function public.dpt_admin_check_in_entry(bigint,bigint,integer,integer,integer,integer,integer,integer) from anon;
grant execute on function public.dpt_admin_check_in_entry(bigint,bigint,integer,integer,integer,integer,integer,integer) to authenticated;

commit;
