begin;

-- Domain players intentionally remain independent of auth.users.  These columns are
-- private operational data; identity credentials and security-sensitive flags are never merged.
alter table public.profiles
  add column if not exists phone text,
  add column if not exists address_line1 text,
  add column if not exists address_line2 text,
  add column if not exists city text,
  add column if not exists state text,
  add column if not exists postal_code text,
  add column if not exists facebook_url text,
  add column if not exists twitter_url text,
  add column if not exists instagram_url text,
  add column if not exists registration_exception boolean not null default false,
  add column if not exists registration_exception_reason text,
  add column if not exists merged_into uuid references public.profiles(id),
  add column if not exists merged_at timestamptz,
  add column if not exists merged_by uuid references public.profiles(id),
  add column if not exists merge_snapshot jsonb not null default '{}'::jsonb;

-- Case-insensitive uniqueness is required for contacts, but historical blank values are allowed.
create unique index if not exists profiles_email_new_active_unique
  on public.profiles (lower(email)) where email is not null and deleted_at is null and legacy_user_id is null;
create unique index if not exists profiles_mobile_new_active_unique
  on public.profiles (mobile) where mobile is not null and deleted_at is null and legacy_user_id is null;
alter table public.profiles drop constraint if exists profiles_player_contact_check;
alter table public.profiles add constraint profiles_player_contact_check check (
  legacy_user_id is not null or
  (first_name is null and last_name is null) or
  (btrim(coalesce(first_name, '')) <> '' and btrim(coalesce(last_name, '')) <> '' and
   (nullif(btrim(coalesce(email, '')), '') is not null or nullif(btrim(coalesce(mobile, '')), '') is not null or registration_exception))
) not valid;

create table if not exists public.admin_roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  display_name text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.admin_permissions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  display_name text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.admin_role_permissions (
  role_id bigint not null references public.admin_roles(id) on delete cascade,
  permission_id bigint not null references public.admin_permissions(id) on delete cascade,
  primary key (role_id, permission_id)
);
create table if not exists public.profile_admin_roles (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role_id bigint not null references public.admin_roles(id) on delete cascade,
  primary key (profile_id, role_id)
);
insert into public.admin_roles(name, display_name) values
 ('super_admin','Super Admin'), ('administrator','Administrator'), ('host','Host'), ('venue','Venue'), ('user','User') on conflict (name) do nothing;
insert into public.admin_permissions(name, display_name) values
 ('list_players','List Players'), ('manage_players','Manage Players'), ('delete_players','Delete Players'),
 ('duplicate_list_players','Fix Duplicate Players'), ('merge_account_players','Merge Accounts'),
 ('manage_roles','Roles'), ('manage_permissions','Permissions'), ('manage_notifications','Notifications')
on conflict (name) do nothing;
insert into public.admin_role_permissions(role_id, permission_id)
select r.id, p.id from public.admin_roles r cross join public.admin_permissions p
where r.name in ('super_admin','administrator') on conflict do nothing;

create or replace function private.has_permission(p_permission text)
returns boolean language sql stable security definer set search_path = pg_catalog, public, private as $$
  select exists (
    select 1 from public.profile_admin_roles par
    join public.admin_role_permissions arp on arp.role_id = par.role_id
    join public.admin_permissions permission on permission.id = arp.permission_id
    join public.profiles profile on profile.id = par.profile_id
    where profile.auth_user_id = auth.uid() and permission.name = p_permission
  ) or exists (
    select 1 from public.profile_roles pr join public.profiles profile on profile.id = pr.profile_id
    where profile.auth_user_id = auth.uid() and pr.role in ('super_admin','administrator')
  )
$$;

alter table public.admin_roles enable row level security;
alter table public.admin_permissions enable row level security;
alter table public.admin_role_permissions enable row level security;
alter table public.profile_admin_roles enable row level security;
create policy "admin roles visible to operators" on public.admin_roles for select to authenticated using (private.is_admin_operator());
create policy "admin permissions visible to operators" on public.admin_permissions for select to authenticated using (private.is_admin_operator());
create policy "admin role permissions visible to operators" on public.admin_role_permissions for select to authenticated using (private.is_admin_operator());
create policy "profile admin roles visible to role managers" on public.profile_admin_roles for select to authenticated using (private.has_permission('manage_roles'));
revoke all on public.admin_roles, public.admin_permissions, public.admin_role_permissions, public.profile_admin_roles from anon;
grant select on public.admin_roles, public.admin_permissions, public.admin_role_permissions, public.profile_admin_roles to authenticated;

create table if not exists public.profile_notification_preferences (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  email_enabled boolean not null default true,
  sms_enabled boolean not null default false,
  push_enabled boolean not null default false,
  tournament_updates boolean not null default true,
  marketing_enabled boolean not null default false,
  updated_at timestamptz not null default now()
);
create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(), profile_id uuid references public.profiles(id) on delete set null,
  channel text not null check (channel in ('email','sms','push','internal')), subject text, body text not null,
  status text not null default 'queued', created_at timestamptz not null default now(), sent_at timestamptz
);
alter table public.profile_notification_preferences enable row level security;
alter table public.notifications enable row level security;
create policy "preferences visible to owner or administrators" on public.profile_notification_preferences for select to authenticated using (profile_id=(select id from public.profiles where auth_user_id=auth.uid() limit 1) or private.is_admin_operator());
create policy "notifications visible to owner or administrators" on public.notifications for select to authenticated using (profile_id=(select id from public.profiles where auth_user_id=auth.uid() limit 1) or private.is_admin_operator());
revoke all on public.profile_notification_preferences, public.notifications from anon;
grant select on public.profile_notification_preferences, public.notifications to authenticated;

create table if not exists public.player_merges (
  id uuid primary key default gen_random_uuid(), idempotency_key uuid not null unique,
  primary_profile_id uuid not null references public.profiles(id), secondary_profile_ids uuid[] not null,
  actor_profile_id uuid references public.profiles(id), dry_run boolean not null default false,
  result jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create table if not exists public.player_merge_sources (
  merge_id uuid not null references public.player_merges(id) on delete cascade,
  source_profile_id uuid not null references public.profiles(id), snapshot jsonb not null,
  primary key (merge_id, source_profile_id)
);
create table if not exists public.player_merge_pending_references (
  merge_id uuid not null references public.player_merges(id) on delete cascade,
  source_profile_id uuid not null references public.profiles(id), reference_type text not null,
  reference_value text not null, primary key (merge_id, source_profile_id, reference_type, reference_value)
);
alter table public.player_merges enable row level security;
alter table public.player_merge_sources enable row level security;
alter table public.player_merge_pending_references enable row level security;
create policy "player merges readable by permitted admins" on public.player_merges for select to authenticated using (private.has_permission('duplicate_list_players'));
create policy "player merge sources readable by permitted admins" on public.player_merge_sources for select to authenticated using (private.has_permission('duplicate_list_players'));
create policy "player merge references readable by permitted admins" on public.player_merge_pending_references for select to authenticated using (private.has_permission('duplicate_list_players'));
revoke all on public.player_merges, public.player_merge_sources, public.player_merge_pending_references from anon;
grant select on public.player_merges, public.player_merge_sources, public.player_merge_pending_references to authenticated;

create or replace function public.dpt_admin_save_player(p_id uuid, p_values jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare actor uuid; before_row jsonb; after_row jsonb; player_id uuid; email_value text:=nullif(lower(btrim(p_values->>'email')),''); mobile_value text:=nullif(btrim(p_values->>'mobile'),'');
begin
 if not private.has_permission('manage_players') then raise exception 'permission denied' using errcode='42501'; end if;
 if jsonb_typeof(p_values)<>'object' or nullif(btrim(p_values->>'first_name'),'') is null or nullif(btrim(p_values->>'last_name'),'') is null then raise exception 'First and last name are required' using errcode='22023'; end if;
 if email_value is null and mobile_value is null and not coalesce((p_values->>'registration_exception')::boolean,false) then raise exception 'Email, mobile, or registration exception is required' using errcode='22023'; end if;
 select id into actor from public.profiles where auth_user_id=auth.uid() and deleted_at is null limit 1;
 if actor is null then raise exception 'Active operator profile required' using errcode='42501'; end if;
 perform pg_advisory_xact_lock(hashtextextended('dpt-player:'||coalesce(p_id::text,email_value,mobile_value,gen_random_uuid()::text),0));
 if exists(select 1 from public.profiles where lower(email)=email_value and deleted_at is null and id is distinct from p_id) then raise exception 'Email already exists' using errcode='23505'; end if;
 if exists(select 1 from public.profiles where mobile=mobile_value and deleted_at is null and id is distinct from p_id) then raise exception 'Mobile already exists' using errcode='23505'; end if;
 if p_id is null then
  insert into public.profiles(first_name,last_name,nick_name,email,mobile,country_code,alias,avatar_url,status,phone,address_line1,address_line2,city,state,postal_code,facebook_url,twitter_url,instagram_url,registration_exception,registration_exception_reason)
  values(btrim(p_values->>'first_name'),btrim(p_values->>'last_name'),nullif(btrim(p_values->>'nick_name'),''),email_value,mobile_value,nullif(btrim(p_values->>'country_code'),''),coalesce(nullif(btrim(p_values->>'alias'),''),trim(both '-' from regexp_replace(lower(btrim((p_values->>'first_name')||'-'||(p_values->>'last_name'))),'[^a-z0-9]+','-','g'))||'-'||substr(gen_random_uuid()::text,1,8)),nullif(btrim(p_values->>'avatar_url'),''),'active',mobile_value,nullif(btrim(p_values->>'address_line1'),''),nullif(btrim(p_values->>'address_line2'),''),nullif(btrim(p_values->>'city'),''),nullif(btrim(p_values->>'state'),''),nullif(btrim(p_values->>'postal_code'),''),nullif(btrim(p_values->>'facebook_url'),''),nullif(btrim(p_values->>'twitter_url'),''),nullif(btrim(p_values->>'instagram_url'),''),coalesce((p_values->>'registration_exception')::boolean,false),nullif(btrim(p_values->>'registration_exception_reason'),'')) returning id,to_jsonb(profiles.*) into player_id,after_row;
  insert into public.profile_roles(profile_id,role) values(player_id,'user') on conflict do nothing;
 else
  select to_jsonb(profile) into before_row from public.profiles profile where id=p_id and deleted_at is null and merged_into is null for update;
  if before_row is null then raise exception 'Player not found'; end if;
  update public.profiles set first_name=btrim(p_values->>'first_name'),last_name=btrim(p_values->>'last_name'),nick_name=nullif(btrim(p_values->>'nick_name'),''),email=email_value,mobile=mobile_value,phone=mobile_value,country_code=nullif(btrim(p_values->>'country_code'),''),alias=coalesce(nullif(btrim(p_values->>'alias'),''),alias),avatar_url=nullif(btrim(p_values->>'avatar_url'),''),address_line1=nullif(btrim(p_values->>'address_line1'),''),address_line2=nullif(btrim(p_values->>'address_line2'),''),city=nullif(btrim(p_values->>'city'),''),state=nullif(btrim(p_values->>'state'),''),postal_code=nullif(btrim(p_values->>'postal_code'),''),facebook_url=nullif(btrim(p_values->>'facebook_url'),''),twitter_url=nullif(btrim(p_values->>'twitter_url'),''),instagram_url=nullif(btrim(p_values->>'instagram_url'),''),registration_exception=coalesce((p_values->>'registration_exception')::boolean,false),registration_exception_reason=nullif(btrim(p_values->>'registration_exception_reason'),''),updated_at=now() where id=p_id returning id,to_jsonb(profiles.*) into player_id,after_row;
 end if;
 insert into public.profile_notification_preferences(profile_id,email_enabled,sms_enabled,tournament_updates,marketing_enabled) values(player_id,coalesce((p_values->>'email_enabled')::boolean,true),coalesce((p_values->>'sms_enabled')::boolean,false),coalesce((p_values->>'tournament_updates')::boolean,true),coalesce((p_values->>'marketing_enabled')::boolean,false)) on conflict(profile_id) do update set email_enabled=excluded.email_enabled,sms_enabled=excluded.sms_enabled,tournament_updates=excluded.tournament_updates,marketing_enabled=excluded.marketing_enabled,updated_at=now();
 insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),actor,case when p_id is null then 'create' else 'update' end,'player',player_id::text,before_row,after_row);
 return after_row;
end $$;

create or replace function public.dpt_admin_archive_player(p_id uuid)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare actor uuid; before_row jsonb; after_row jsonb;
begin
 if not private.has_permission('delete_players') then raise exception 'permission denied' using errcode='42501'; end if;
 select id into actor from public.profiles where auth_user_id=auth.uid() and deleted_at is null limit 1;
 if actor is null or actor=p_id then raise exception 'Cannot archive the current operator' using errcode='42501'; end if;
 perform pg_advisory_xact_lock(hashtextextended('dpt-player:'||p_id::text,0));
 select to_jsonb(profile) into before_row from public.profiles profile where id=p_id and deleted_at is null for update;
 if before_row is null then raise exception 'Player not found'; end if;
 if exists(select 1 from public.tournament_entries where player_id=p_id) then raise exception 'Player has tournament history' using errcode='23503'; end if;
 update public.profiles set status='archived',deleted_at=now(),updated_at=now() where id=p_id returning to_jsonb(profiles.*) into after_row;
 insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),actor,'archive','player',p_id::text,before_row,after_row);
 return after_row;
end $$;

create or replace function public.dpt_admin_save_role(p_id bigint,p_values jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare actor uuid; v_role_id bigint; before_row jsonb; after_row jsonb; permission_names text[];
begin
 if not private.has_permission('manage_roles') then raise exception 'permission denied' using errcode='42501'; end if;
 if nullif(btrim(p_values->>'name'),'') is null or jsonb_typeof(p_values->'permissions')<>'array' or jsonb_array_length(p_values->'permissions')=0 then raise exception 'Role name and permissions are required' using errcode='22023'; end if;
 select id into actor from public.profiles where auth_user_id=auth.uid() and deleted_at is null limit 1;
 select array_agg(value order by value) into permission_names from jsonb_array_elements_text(p_values->'permissions') value;
 if exists(select 1 from unnest(permission_names) as selected(permission_name) left join public.admin_permissions permission on permission.name=selected.permission_name where permission.id is null) then raise exception 'Unknown permission' using errcode='23503'; end if;
 if p_id is null then insert into public.admin_roles(name,display_name) values(lower(regexp_replace(btrim(p_values->>'name'),'[^a-zA-Z0-9]+','_','g')),btrim(p_values->>'name')) returning id,to_jsonb(admin_roles.*) into v_role_id,after_row;
 else select to_jsonb(role) into before_row from public.admin_roles role where id=p_id for update; if before_row is null then raise exception 'Role not found'; end if; if before_row->>'name'='super_admin' then raise exception 'Super Admin is protected' using errcode='42501'; end if; update public.admin_roles set name=lower(regexp_replace(btrim(p_values->>'name'),'[^a-zA-Z0-9]+','_','g')),display_name=btrim(p_values->>'name') where id=p_id returning id,to_jsonb(admin_roles.*) into v_role_id,after_row; end if;
 delete from public.admin_role_permissions mapping where mapping.role_id=v_role_id;
 insert into public.admin_role_permissions(role_id,permission_id) select v_role_id,permission.id from public.admin_permissions permission where permission.name=any(permission_names) on conflict do nothing;
 insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),actor,case when p_id is null then 'create' else 'update' end,'admin_role',v_role_id::text,before_row,after_row||jsonb_build_object('permissions',permission_names));
 return after_row||jsonb_build_object('permissions',permission_names);
end $$;

create or replace function public.dpt_admin_delete_role(p_id bigint)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare actor uuid; before_row jsonb;
begin
 if not private.has_permission('manage_roles') then raise exception 'permission denied' using errcode='42501'; end if;
 select id into actor from public.profiles where auth_user_id=auth.uid() and deleted_at is null limit 1;
 select to_jsonb(role) into before_row from public.admin_roles role where id=p_id for update;
 if before_row is null then raise exception 'Role not found'; end if;
 if before_row->>'name' in ('super_admin','administrator') or exists(select 1 from public.profile_admin_roles where role_id=p_id) then raise exception 'Protected or assigned role cannot be deleted' using errcode='23503'; end if;
 delete from public.admin_roles where id=p_id;
 insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),actor,'delete','admin_role',p_id::text,before_row,null);
 return before_row;
end $$;

revoke all on function public.dpt_admin_save_player(uuid,jsonb), public.dpt_admin_archive_player(uuid), public.dpt_admin_save_role(bigint,jsonb), public.dpt_admin_delete_role(bigint) from public,anon;
grant execute on function public.dpt_admin_save_player(uuid,jsonb), public.dpt_admin_archive_player(uuid), public.dpt_admin_save_role(bigint,jsonb), public.dpt_admin_delete_role(bigint) to authenticated;

create or replace function public.dpt_admin_merge_players(p_primary uuid, p_secondaries uuid[], p_idempotency uuid, p_dry_run boolean default false)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public, private as $$
declare actor uuid; merge_id uuid; source uuid; existing jsonb; moved integer := 0; changed integer := 0; primary_row public.profiles%rowtype; source_row public.profiles%rowtype;
begin
  if not private.has_permission('merge_account_players') then raise exception 'permission denied'; end if;
  if p_primary is null or coalesce(array_length(p_secondaries,1),0)=0 or p_primary = any(p_secondaries) or p_secondaries @> array[p_primary] or cardinality(p_secondaries)<>(select count(distinct value) from unnest(p_secondaries) value) then raise exception 'invalid merge selection'; end if;
  select id into actor from public.profiles where auth_user_id = auth.uid();
  perform pg_advisory_xact_lock(hashtextextended(array_to_string(array(select x::text from unnest(array_append(p_secondaries,p_primary)) x order by x), ','), 0));
  select result into existing from public.player_merges where idempotency_key=p_idempotency;
  if found then return existing; end if;
  select * into primary_row from public.profiles where id=p_primary and deleted_at is null and merged_into is null for update;
  if not found then raise exception 'primary player is unavailable'; end if;
  if exists (select 1 from unnest(p_secondaries) s left join public.profiles secondary_profile on secondary_profile.id=s where secondary_profile.id is null or secondary_profile.deleted_at is not null or secondary_profile.merged_into is not null) then raise exception 'secondary player is unavailable'; end if;
  perform 1 from public.profiles where id=any(p_secondaries) for update;
  insert into public.player_merges(idempotency_key,primary_profile_id,secondary_profile_ids,actor_profile_id,dry_run,result)
  values(p_idempotency,p_primary,(select array_agg(distinct x order by x) from unnest(p_secondaries) x),actor,p_dry_run,'{}') returning id into merge_id;
  foreach source in array p_secondaries loop
    select * into source_row from public.profiles where id=source;
    insert into public.player_merge_sources(merge_id,source_profile_id,snapshot) values(merge_id,source,to_jsonb(source_row));
    -- Retain immutable historical entry ids. If two entries collide, highest score wins; secondary wins a tie.
    update public.tournament_entries losing set duplicate_status=false
    from public.tournament_entries incoming
    where incoming.player_id=source and losing.player_id=p_primary and losing.tournament_id=incoming.tournament_id
      and coalesce(incoming.score,0) >= coalesce(losing.score,0);
    update public.tournament_entries incoming set duplicate_status=false
    from public.tournament_entries retained
    where incoming.player_id=source and retained.player_id=p_primary and retained.tournament_id=incoming.tournament_id
      and coalesce(incoming.score,0) < coalesce(retained.score,0);
    update public.tournament_entries e set player_id=p_primary
    where e.player_id=source and not exists (select 1 from public.tournament_entries other where other.player_id=p_primary and other.tournament_id=e.tournament_id);
    get diagnostics changed = row_count;
    moved := moved + changed;
    update public.tournament_entry_addons set player_id=p_primary where player_id=source;
    update public.flight_advancements set player_id=p_primary where player_id=source and not exists (select 1 from public.flight_advancements f where f.player_id=p_primary and f.flight_tournament_id=flight_advancements.flight_tournament_id and f.main_tournament_id=flight_advancements.main_tournament_id);
    update public.profiles set first_name=coalesce(nullif(btrim(primary_row.first_name),''),nullif(btrim(source_row.first_name),'')), last_name=coalesce(nullif(btrim(primary_row.last_name),''),nullif(btrim(source_row.last_name),'')), nick_name=coalesce(nullif(btrim(primary_row.nick_name),''),nullif(btrim(source_row.nick_name),'')), mobile=coalesce(nullif(btrim(primary_row.mobile),''),nullif(btrim(source_row.mobile),'')), address_line1=coalesce(nullif(btrim(primary_row.address_line1),''),nullif(btrim(source_row.address_line1),'')) where id=p_primary;
    update public.profiles set status='merged', merged_into=p_primary, merged_at=now(), merged_by=actor, deleted_at=now(), merge_snapshot=to_jsonb(source_row) where id=source;
  end loop;
  if p_dry_run then raise exception 'dry-run rollback'; end if;
  update public.player_merges set result=jsonb_build_object('merge_id',merge_id,'primary_profile_id',p_primary,'secondary_profile_ids',p_secondaries,'entries_transferred',moved) where id=merge_id;
  insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,before_data,after_data) values(auth.uid(),actor,'merge','player',p_primary::text,jsonb_build_object('primary',to_jsonb(primary_row),'secondaries',p_secondaries),(select result from public.player_merges where id=merge_id));
  return (select result from public.player_merges where id=merge_id);
exception when others then
  if sqlerrm = 'dry-run rollback' then return jsonb_build_object('dry_run',true,'primary_profile_id',p_primary,'secondary_profile_ids',p_secondaries,'entries_would_transfer',moved); end if;
  raise;
end $$;
revoke all on function public.dpt_admin_merge_players(uuid,uuid[],uuid,boolean) from public, anon;
grant execute on function public.dpt_admin_merge_players(uuid,uuid[],uuid,boolean) to authenticated;
commit;
