begin;

-- Staging is intentionally simulation-only. This constant is database owned; clients never choose a transport.
alter table public.notification_campaigns add column if not exists purpose text not null default 'general' check (purpose in ('general','tournament_update','marketing'));
alter table public.notification_campaigns add column if not exists external_delivery_mode text not null default 'simulated' check (external_delivery_mode = 'simulated');
alter table public.notification_campaigns add column if not exists started_at timestamptz;
alter table public.notification_campaigns add column if not exists completed_at timestamptz;
alter table public.notification_campaigns add column if not exists cancelled_at timestamptz;
alter table public.notification_campaigns drop constraint if exists notification_campaigns_status_check;
alter table public.notification_campaigns add constraint notification_campaigns_status_check check (status in ('queued','processing','completed','completed_with_failures','cancelled'));

alter table public.notification_deliveries add column if not exists delivery_variant text not null default 'recipient' check (delivery_variant in ('recipient','sender_copy'));
alter table public.notification_deliveries add column if not exists attempts integer not null default 0 check (attempts >= 0 and attempts <= 10);
alter table public.notification_deliveries add column if not exists max_attempts integer not null default 5 check (max_attempts between 1 and 10);
alter table public.notification_deliveries add column if not exists next_attempt_at timestamptz;
alter table public.notification_deliveries add column if not exists last_attempt_at timestamptz;
alter table public.notification_deliveries add column if not exists error_code text;
alter table public.notification_deliveries add column if not exists suppression_reason text;
alter table public.notification_deliveries add column if not exists lease_token uuid;
alter table public.notification_deliveries add column if not exists lease_expires_at timestamptz;
alter table public.notification_deliveries add column if not exists worker_id text;
alter table public.notification_deliveries add column if not exists provider_message_id text;
alter table public.notification_deliveries add column if not exists simulated boolean not null default true check (simulated);
alter table public.notification_deliveries drop constraint if exists notification_deliveries_status_check;
alter table public.notification_deliveries add constraint notification_deliveries_status_check check (status in ('queued','sending','sent','failed','suppressed'));
alter table public.notification_deliveries drop constraint if exists notification_deliveries_campaign_id_profile_id_channel_key;
alter table public.notification_deliveries add constraint notification_delivery_variant_unique unique(campaign_id,profile_id,channel,delivery_variant);
create index if not exists notification_deliveries_claim_idx on public.notification_deliveries(status,next_attempt_at,lease_expires_at) where status in ('queued','sending');

create table if not exists public.notification_delivery_attempts (
 id uuid primary key default gen_random_uuid(), delivery_id uuid not null references public.notification_deliveries(id) on delete cascade,
 attempt_number integer not null check (attempt_number between 1 and 10), outcome text not null check(outcome in ('sent','failed','suppressed')),
 error_code text, provider_message_id text, simulated boolean not null default true check(simulated), worker_id text not null, created_at timestamptz not null default now(),
 unique(delivery_id,attempt_number)
);
create table if not exists public.profile_channel_suppressions (
 profile_id uuid not null references public.profiles(id) on delete cascade, channel text not null check(channel in ('email','sms')),
 reason text not null check(btrim(reason)<>''), created_at timestamptz not null default now(), expires_at timestamptz,
 primary key(profile_id,channel)
);
create table if not exists public.notification_rate_windows (
 channel text not null check(channel in ('email','sms')), window_started_at timestamptz not null, sent_count integer not null default 0 check(sent_count >= 0),
 primary key(channel,window_started_at)
);
alter table public.notification_delivery_attempts enable row level security;
alter table public.profile_channel_suppressions enable row level security;
alter table public.notification_rate_windows enable row level security;
create policy "delivery attempts operators" on public.notification_delivery_attempts for select to authenticated using(private.has_permission('manage_notifications'));
create policy "channel suppressions operators" on public.profile_channel_suppressions for select to authenticated using(private.has_permission('manage_notifications'));
revoke all on public.notification_delivery_attempts,public.profile_channel_suppressions,public.notification_rate_windows from anon,authenticated;
grant select on public.notification_delivery_attempts,public.profile_channel_suppressions to authenticated;

create or replace function public.dpt_admin_create_notification(p_values jsonb,p_idempotency uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare actor uuid:=private.dpt_actor(); campaign uuid; existing jsonb; target_ids uuid[]; target jsonb:=coalesce(p_values->'target','{}'::jsonb); dry_run boolean:=coalesce((p_values->>'dry_run')::boolean,false); recipient_count integer; queued_count integer; suppressed_count integer;
begin
 if not private.has_permission('manage_notifications') or actor is null then raise exception 'permission denied' using errcode='42501'; end if; perform private.require_content_object(p_values);
 if nullif(btrim(p_values->>'title'),'') is null or nullif(btrim(p_values->>'message_html'),'') is null then raise exception 'title and message required' using errcode='22023'; end if;
 if coalesce((p_values->>'sms_enabled')::boolean,false) and nullif(btrim(p_values->>'sms_body'),'') is null then raise exception 'SMS body required' using errcode='22023'; end if;
 if coalesce(nullif(p_values->>'purpose',''),'general') not in ('general','tournament_update','marketing') then raise exception 'invalid campaign purpose' using errcode='22023'; end if;
 if coalesce(jsonb_array_length(coalesce(p_values->'profile_ids','[]'::jsonb)),0)=0 and coalesce(jsonb_array_length(coalesce(target->'venue_ids','[]'::jsonb)),0)=0 and coalesce(jsonb_array_length(coalesce(target->'season_ids','[]'::jsonb)),0)=0 and coalesce(jsonb_array_length(coalesce(target->'event_ids','[]'::jsonb)),0)=0 and coalesce(jsonb_array_length(coalesce(target->'league_ids','[]'::jsonb)),0)=0 and coalesce(jsonb_array_length(coalesce(target->'tournament_ids','[]'::jsonb)),0)=0 and coalesce(jsonb_array_length(coalesce(target->'role_names','[]'::jsonb)),0)=0 then raise exception 'at least one target is required' using errcode='22023'; end if;
 with candidates as (select distinct p.id from public.profiles p where p.deleted_at is null and p.merged_into is null and p.status='active' and ((coalesce(jsonb_array_length(coalesce(p_values->'profile_ids','[]'::jsonb)),0)>0 and p.id in(select value::uuid from jsonb_array_elements_text(p_values->'profile_ids') value)) or (coalesce(jsonb_array_length(coalesce(p_values->'profile_ids','[]'::jsonb)),0)=0 and (coalesce(jsonb_array_length(coalesce(target->'venue_ids','[]'::jsonb)),0)=0 or exists(select 1 from public.tournament_entries e join public.tournaments t on t.id=e.tournament_id where e.player_id=p.id and t.venue_id in(select value::bigint from jsonb_array_elements_text(target->'venue_ids') value))) and (coalesce(jsonb_array_length(coalesce(target->'season_ids','[]'::jsonb)),0)=0 or exists(select 1 from public.tournament_entries e join public.tournaments t on t.id=e.tournament_id join public.events ev on ev.id=t.event_id where e.player_id=p.id and ev.season_id in(select value::bigint from jsonb_array_elements_text(target->'season_ids') value))) and (coalesce(jsonb_array_length(coalesce(target->'event_ids','[]'::jsonb)),0)=0 or exists(select 1 from public.tournament_entries e join public.tournaments t on t.id=e.tournament_id where e.player_id=p.id and t.event_id in(select value::bigint from jsonb_array_elements_text(target->'event_ids') value))) and (coalesce(jsonb_array_length(coalesce(target->'league_ids','[]'::jsonb)),0)=0 or exists(select 1 from public.tournament_entries e join public.tournaments t on t.id=e.tournament_id join public.events ev on ev.id=t.event_id join public.seasons s on s.id=ev.season_id where e.player_id=p.id and s.league_id in(select value::bigint from jsonb_array_elements_text(target->'league_ids') value))) and (coalesce(jsonb_array_length(coalesce(target->'tournament_ids','[]'::jsonb)),0)=0 or exists(select 1 from public.tournament_entries e where e.player_id=p.id and e.tournament_id in(select value::bigint from jsonb_array_elements_text(target->'tournament_ids') value))) and (coalesce(jsonb_array_length(coalesce(target->'role_names','[]'::jsonb)),0)=0 or exists(select 1 from public.profile_roles r where r.profile_id=p.id and r.role::text in(select value from jsonb_array_elements_text(target->'role_names') value)))))), including_sender as (select id from candidates union select actor) select array_agg(id order by id) into target_ids from including_sender;
 recipient_count:=coalesce(cardinality(target_ids),0);
 -- Preview has no writes and still exposes exact eligibility totals.
 select count(*) filter(where eligible),count(*) filter(where not eligible) into queued_count,suppressed_count from (select p.id,c.channel, case when c.channel='email' then p.email is not null and coalesce((p.legacy_data->>'verified_email')::boolean,false) and coalesce(pref.email_enabled,true) else p.mobile is not null and coalesce((p.legacy_data->>'verified_phone')::boolean,false) and coalesce(pref.sms_enabled,false) end and not exists(select 1 from public.profile_channel_suppressions s where s.profile_id=p.id and s.channel=c.channel and (s.expires_at is null or s.expires_at>now())) as eligible from public.profiles p left join public.profile_notification_preferences pref on pref.profile_id=p.id cross join lateral unnest(array_remove(array[case when coalesce((p_values->>'email_enabled')::boolean,false) then 'email' end,case when coalesce((p_values->>'sms_enabled')::boolean,false) then 'sms' end],null)) c(channel) where p.id=any(coalesce(target_ids,array[]::uuid[]))) x;
 if dry_run then return jsonb_build_object('status','preview','recipients',recipient_count,'queued',coalesce(queued_count,0),'suppressed',coalesce(suppressed_count,0),'external_delivery_mode','simulated'); end if;
 select jsonb_build_object('id',id,'status',status,'recipients',(select count(*) from public.notification_recipients where campaign_id=notification_campaigns.id),'external_delivery_mode','simulated') into existing from public.notification_campaigns where idempotency_key=p_idempotency; if existing is not null then return existing; end if;
 insert into public.notification_campaigns(idempotency_key,title,message_html,email_enabled,sms_enabled,sms_body,target,sender_profile_id,status,purpose,external_delivery_mode) values(p_idempotency,btrim(p_values->>'title'),private.sanitize_html(p_values->>'message_html'),coalesce((p_values->>'email_enabled')::boolean,false),coalesce((p_values->>'sms_enabled')::boolean,false),nullif(btrim(p_values->>'sms_body'),''),target,actor,'queued',coalesce(nullif(p_values->>'purpose',''),'general'),'simulated') returning id into campaign;
 insert into public.notification_recipients(campaign_id,profile_id,recipient_snapshot,channels) select campaign,p.id,jsonb_build_object('id',p.id,'name',concat_ws(' ',p.first_name,p.last_name)),array_remove(array['internal',case when coalesce((p_values->>'email_enabled')::boolean,false) then 'email' end,case when coalesce((p_values->>'sms_enabled')::boolean,false) then 'sms' end],null) from public.profiles p where p.id=any(coalesce(target_ids,array[]::uuid[]));
 insert into public.internal_notifications(campaign_id,profile_id,title,message_html) select campaign,r.profile_id,btrim(p_values->>'title'),private.sanitize_html(p_values->>'message_html') from public.notification_recipients r where r.campaign_id=campaign;
 insert into public.notification_deliveries(campaign_id,profile_id,channel,status,sent_at,delivery_variant,simulated) select campaign,r.profile_id,'internal','sent',now(),'recipient',true from public.notification_recipients r where r.campaign_id=campaign;
 insert into public.notification_deliveries(campaign_id,profile_id,channel,status,next_attempt_at,suppression_reason,delivery_variant,simulated) select campaign,p.id,c.channel,case when eligible then 'queued' else 'suppressed' end,case when eligible then now() end,case when eligible then null when c.channel='email' and p.email is null then 'missing_destination' when c.channel='sms' and p.mobile is null then 'missing_destination' when c.channel='email' and not coalesce((p.legacy_data->>'verified_email')::boolean,false) then 'unverified_destination' when c.channel='sms' and not coalesce((p.legacy_data->>'verified_phone')::boolean,false) then 'unverified_destination' when s.profile_id is not null then 'provider_or_admin_suppression' else 'preference_disabled' end,'recipient',true from public.notification_recipients r join public.profiles p on p.id=r.profile_id cross join lateral unnest(array_remove(array[case when coalesce((p_values->>'email_enabled')::boolean,false) then 'email' end,case when coalesce((p_values->>'sms_enabled')::boolean,false) then 'sms' end],null)) c(channel) left join public.profile_notification_preferences pref on pref.profile_id=p.id left join public.profile_channel_suppressions s on s.profile_id=p.id and s.channel=c.channel and (s.expires_at is null or s.expires_at>now()) cross join lateral (select (case when c.channel='email' then p.email is not null and coalesce((p.legacy_data->>'verified_email')::boolean,false) and coalesce(pref.email_enabled,true) else p.mobile is not null and coalesce((p.legacy_data->>'verified_phone')::boolean,false) and coalesce(pref.sms_enabled,false) end and s.profile_id is null) eligible) e where r.campaign_id=campaign;
 update public.notification_campaigns set status='completed',started_at=now(),completed_at=now() where id=campaign and not exists(select 1 from public.notification_deliveries where campaign_id=campaign and status in ('queued','sending'));
 insert into public.dpt_admin_audit_log(actor_auth_user_id,actor_profile_id,action,entity_type,entity_id,after_data) values(auth.uid(),actor,'create','notification_campaign',campaign::text,jsonb_build_object('external_delivery_mode','simulated','recipients',recipient_count));
 return jsonb_build_object('id',campaign,'status',(select status from public.notification_campaigns where id=campaign),'recipients',recipient_count,'queued',coalesce(queued_count,0),'suppressed',coalesce(suppressed_count,0),'external_delivery_mode','simulated');
end $$;

create or replace function public.dpt_admin_claim_notification_deliveries(p_campaign_id uuid,p_limit integer default 25) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare actor uuid:=private.dpt_actor(); v_limit integer:=least(greatest(coalesce(p_limit,25),1),25); token uuid:=gen_random_uuid(); claimed jsonb; window_start timestamptz:=date_trunc('minute',now()); email_remaining integer; sms_remaining integer; email_ids uuid[]:='{}'::uuid[]; sms_ids uuid[]:='{}'::uuid[]; picked_ids uuid[]:='{}'::uuid[];
begin
 if not private.has_permission('manage_notifications') or actor is null then raise exception 'permission denied' using errcode='42501'; end if;
 if not exists(select 1 from public.notification_campaigns where id=p_campaign_id and status not in ('cancelled','completed','completed_with_failures') for update) then raise exception 'campaign is not processable' using errcode='22023'; end if;
 insert into public.notification_rate_windows(channel,window_started_at,sent_count) values('email',window_start,0),('sms',window_start,0) on conflict do nothing;
 perform 1 from public.notification_rate_windows where window_started_at=window_start order by channel for update;
 select greatest(0,30-sent_count) into email_remaining from public.notification_rate_windows where channel='email' and window_started_at=window_start;
 select greatest(0,10-sent_count) into sms_remaining from public.notification_rate_windows where channel='sms' and window_started_at=window_start;
 update public.notification_deliveries set status='queued',lease_token=null,lease_expires_at=null,worker_id=null,next_attempt_at=now() where campaign_id=p_campaign_id and status='sending' and lease_expires_at<now();
 select coalesce(array_agg(id),'{}'::uuid[]) into email_ids from (select d.id from public.notification_deliveries d where d.campaign_id=p_campaign_id and d.channel='email' and d.status='queued' and coalesce(d.next_attempt_at,now())<=now() and d.attempts<d.max_attempts order by d.next_attempt_at,d.created_at,d.id for update skip locked limit least(v_limit,email_remaining)) selected;
 select coalesce(array_agg(id),'{}'::uuid[]) into sms_ids from (select d.id from public.notification_deliveries d where d.campaign_id=p_campaign_id and d.channel='sms' and d.status='queued' and coalesce(d.next_attempt_at,now())<=now() and d.attempts<d.max_attempts order by d.next_attempt_at,d.created_at,d.id for update skip locked limit least(greatest(v_limit-cardinality(email_ids),0),sms_remaining)) selected;
 picked_ids:=email_ids||sms_ids;
 with updated as (update public.notification_deliveries d set status='sending',lease_token=token,lease_expires_at=now()+interval '5 minutes',worker_id='staging-simulator',last_attempt_at=now() where d.id=any(picked_ids) returning d.id,d.channel,d.profile_id,d.campaign_id,d.lease_token) select coalesce(jsonb_agg(to_jsonb(updated)),'[]'::jsonb) into claimed from updated;
 update public.notification_rate_windows r set sent_count=sent_count+(select count(*) from public.notification_deliveries d where d.lease_token=token and d.channel=r.channel) where r.window_started_at=window_start;
 update public.notification_campaigns set status='processing',started_at=coalesce(started_at,now()) where id=p_campaign_id and status='queued';
 return jsonb_build_object('lease_token',token,'deliveries',claimed,'mode','simulated','limits',jsonb_build_object('email_per_minute',30,'sms_per_minute',10,'batch',v_limit));
end $$;

create or replace function public.dpt_admin_finalize_notification_delivery(p_delivery_id uuid,p_lease_token uuid,p_outcome text,p_provider_message_id text default null,p_error_code text default null) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare actor uuid:=private.dpt_actor(); d public.notification_deliveries%rowtype; next_at timestamptz; final_status text; result jsonb;
begin if not private.has_permission('manage_notifications') or actor is null then raise exception 'permission denied' using errcode='42501'; end if; if p_outcome not in ('sent','failed','suppressed') then raise exception 'invalid outcome' using errcode='22023'; end if;
 select * into d from public.notification_deliveries where id=p_delivery_id for update; if not found or d.status<>'sending' or d.lease_token<>p_lease_token or d.lease_expires_at<now() then raise exception 'delivery lease unavailable' using errcode='40901'; end if;
 if p_outcome='failed' and d.attempts+1<d.max_attempts then final_status:='queued'; next_at:=now()+make_interval(secs=>least(3600,30*(2^d.attempts)::integer)); else final_status:=p_outcome; next_at:=null; end if;
 update public.notification_deliveries set attempts=attempts+1,status=final_status,next_attempt_at=next_at,last_attempt_at=now(),sent_at=case when p_outcome='sent' then now() else sent_at end,error_code=case when p_outcome='failed' then coalesce(p_error_code,'simulation_failed') else null end,suppression_reason=case when p_outcome='suppressed' then coalesce(p_error_code,'simulated_suppression') else suppression_reason end,provider_message_id=case when p_outcome='sent' then p_provider_message_id else provider_message_id end,lease_token=null,lease_expires_at=null,worker_id=null where id=p_delivery_id returning to_jsonb(notification_deliveries.*) into result;
 insert into public.notification_delivery_attempts(delivery_id,attempt_number,outcome,error_code,provider_message_id,simulated,worker_id) values(p_delivery_id,d.attempts+1,p_outcome,p_error_code,p_provider_message_id,true,'staging-simulator');
 update public.notification_campaigns c set status=case when exists(select 1 from public.notification_deliveries x where x.campaign_id=c.id and x.status in ('queued','sending')) then 'processing' when exists(select 1 from public.notification_deliveries x where x.campaign_id=c.id and x.status='failed') then 'completed_with_failures' else 'completed' end,completed_at=case when not exists(select 1 from public.notification_deliveries x where x.campaign_id=c.id and x.status in ('queued','sending')) then now() else null end where c.id=d.campaign_id and c.status<>'cancelled'; return result; end $$;

create or replace function public.dpt_admin_cancel_notification_campaign(p_campaign_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare actor uuid:=private.dpt_actor(); result jsonb; begin if not private.has_permission('manage_notifications') or actor is null then raise exception 'permission denied' using errcode='42501'; end if; update public.notification_deliveries set status='suppressed',suppression_reason='campaign_cancelled',lease_token=null,lease_expires_at=null where campaign_id=p_campaign_id and status in ('queued','sending'); update public.notification_campaigns set status='cancelled',cancelled_at=now(),completed_at=now() where id=p_campaign_id returning to_jsonb(notification_campaigns.*) into result; if result is null then raise exception 'campaign not found'; end if; return result; end $$;
create or replace function public.dpt_admin_retry_notification_delivery(p_delivery_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare actor uuid:=private.dpt_actor(); result jsonb; begin if not private.has_permission('manage_notifications') or actor is null then raise exception 'permission denied' using errcode='42501'; end if; update public.notification_deliveries d set status='queued',max_attempts=least(10,greatest(d.max_attempts,d.attempts+1)),next_attempt_at=now(),error_code=null,lease_token=null,lease_expires_at=null where d.id=p_delivery_id and d.status='failed' and d.attempts<10 and exists(select 1 from public.notification_campaigns c where c.id=d.campaign_id and c.status<>'cancelled') returning to_jsonb(d.*) into result; if result is null then raise exception 'only retryable failed deliveries can be retried'; end if; return result; end $$;
create or replace function public.dpt_admin_notification_campaign_detail(p_campaign_id uuid,p_offset integer default 0,p_limit integer default 100) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare actor uuid:=private.dpt_actor(); result jsonb; begin if not private.has_permission('manage_notifications') or actor is null then raise exception 'permission denied' using errcode='42501'; end if; select jsonb_build_object('campaign',to_jsonb(c),'summary',(select jsonb_object_agg(status,n) from (select status,count(*) n from public.notification_deliveries where campaign_id=c.id group by status)s),'suppressions',(select jsonb_object_agg(coalesce(suppression_reason,'none'),n) from (select suppression_reason,count(*) n from public.notification_deliveries where campaign_id=c.id and status='suppressed' group by suppression_reason)s),'deliveries',coalesce((select jsonb_agg(to_jsonb(d)) from (select d.*,r.recipient_snapshot from public.notification_deliveries d join public.notification_recipients r on r.campaign_id=d.campaign_id and r.profile_id=d.profile_id where d.campaign_id=c.id order by d.created_at,d.id offset greatest(coalesce(p_offset,0),0) limit least(greatest(coalesce(p_limit,100),1),100)) d),'[]'::jsonb),'attempts',coalesce((select jsonb_agg(to_jsonb(a)) from public.notification_delivery_attempts a join public.notification_deliveries d on d.id=a.delivery_id where d.campaign_id=c.id),'[]'::jsonb)) into result from public.notification_campaigns c where c.id=p_campaign_id; if result is null then raise exception 'campaign not found'; end if; return result; end $$;
revoke all on function public.dpt_admin_create_notification(jsonb,uuid),public.dpt_admin_claim_notification_deliveries(uuid,integer),public.dpt_admin_finalize_notification_delivery(uuid,uuid,text,text,text),public.dpt_admin_cancel_notification_campaign(uuid),public.dpt_admin_retry_notification_delivery(uuid),public.dpt_admin_notification_campaign_detail(uuid,integer,integer) from public,anon;
grant execute on function public.dpt_admin_create_notification(jsonb,uuid),public.dpt_admin_claim_notification_deliveries(uuid,integer),public.dpt_admin_finalize_notification_delivery(uuid,uuid,text,text,text),public.dpt_admin_cancel_notification_campaign(uuid),public.dpt_admin_retry_notification_delivery(uuid),public.dpt_admin_notification_campaign_detail(uuid,integer,integer) to authenticated;
commit;
