begin;

-- Loop 2 reset semantics, matching legacy resetTournament while making modern
-- materialized payouts and flight carryover reversible. Entries, add-on history,
-- updates, profiles, roles, and legacy/source identities are retained. Entry
-- operational state is cleared, registration is reopened, and generated payout
-- rows are removed. Audit history is intentionally never reset.
create table if not exists public.dpt_tournament_reset_snapshots (
  id bigint generated by default as identity primary key,
  tournament_id bigint not null references public.tournaments(id) on delete restrict,
  actor_auth_user_id uuid not null references auth.users(id),
  actor_profile_id uuid references public.profiles(id),
  confirmation_token text not null,
  before_data jsonb not null,
  after_data jsonb not null,
  created_at timestamptz not null default now()
);
alter table public.dpt_tournament_reset_snapshots enable row level security;
revoke all on public.dpt_tournament_reset_snapshots from public, anon;
grant select on public.dpt_tournament_reset_snapshots to authenticated;
drop policy if exists "tournament reset snapshots readable by operators" on public.dpt_tournament_reset_snapshots;
create policy "tournament reset snapshots readable by operators"
  on public.dpt_tournament_reset_snapshots for select to authenticated
  using (private.is_admin_operator());

create or replace function public.dpt_admin_tournament_reset_preview(p_tournament_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  tournament_row public.tournaments%rowtype;
  counts jsonb;
  state_text text;
begin
  if auth.uid() is null or not private.is_admin_operator() then
    raise exception 'DPT administrator authorization required' using errcode = '42501';
  end if;
  select * into tournament_row from public.tournaments
  where id = p_tournament_id and deleted_at is null;
  if not found then raise exception 'Tournament not found' using errcode = 'P0002'; end if;

  select jsonb_build_object(
    'entries_cleared', (select count(*) from public.tournament_entries where tournament_id = p_tournament_id and deleted_at is null),
    'addons_preserved', (select count(*) from public.tournament_entry_addons where tournament_id = p_tournament_id),
    'payouts_preserved', (select count(*) from public.tournament_payouts where tournament_id = p_tournament_id),
    'updates_preserved', (select count(*) from public.tournament_updates where tournament_id = p_tournament_id and deleted_at is null),
    'active_flight_advancements_unwound', (select count(*) from public.flight_advancements where undone_at is null and (flight_tournament_id = p_tournament_id or main_tournament_id = p_tournament_id)),
    'flight_provenance_affected', (select count(*) from public.flight_main_entry_provenance where main_tournament_id = p_tournament_id or exists (select 1 from public.flight_advancements a where a.main_tournament_id = flight_main_entry_provenance.main_tournament_id and a.player_id = flight_main_entry_provenance.player_id and a.flight_tournament_id = p_tournament_id)),
    'audit_excluded_related_records', (select count(*) from public.dpt_admin_audit_log where tournament_id = p_tournament_id)
  ) into counts;
  state_text := concat_ws('|', p_tournament_id::text, coalesce(tournament_row.updated_at::text, ''), counts::text);
  return jsonb_build_object(
    'tournament_id', p_tournament_id,
    'tournament_updated_at', tournament_row.updated_at,
    'counts', counts,
    'confirmation_token', md5(state_text),
    'semantics', jsonb_build_object(
      'entries', 'clear operational status; retain identities and financial/add-on history',
      'addons', 'preserved', 'updates', 'preserved', 'payouts', 'preserved',
      'audit', 'excluded from reset and retained', 'registration', 'reopen'
    )
  );
end;
$$;

create or replace function public.dpt_admin_reset_tournament(
  p_tournament_id bigint,
  p_confirmation_token text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  actor_profile_id uuid;
  tournament_row public.tournaments%rowtype;
  expected jsonb;
  before_snapshot jsonb;
  after_counts jsonb;
  link record;
  source public.flight_main_entry_provenance%rowtype;
  remaining_count integer;
  computed_chips integer;
  type_code public.tournament_type_code;
  lock_id bigint;
begin
  if auth.uid() is null or not private.is_admin_operator() then
    raise exception 'DPT administrator authorization required' using errcode = '42501';
  end if;
  if p_confirmation_token is null or p_confirmation_token !~ '^[a-f0-9]{32}$' then
    raise exception 'A valid reset preview confirmation token is required' using errcode = '22023';
  end if;
  select id into actor_profile_id from public.profiles
  where auth_user_id = auth.uid() and status = 'active' and deleted_at is null limit 1;
  if actor_profile_id is null then raise exception 'Active operator profile required' using errcode = '42501'; end if;

  for lock_id in
    select distinct locked_id
    from (
      select p_tournament_id as locked_id
      union all
      select advancement.flight_tournament_id from public.flight_advancements advancement
        where advancement.undone_at is null and (advancement.flight_tournament_id = p_tournament_id or advancement.main_tournament_id = p_tournament_id)
      union all
      select advancement.main_tournament_id from public.flight_advancements advancement
        where advancement.undone_at is null and (advancement.flight_tournament_id = p_tournament_id or advancement.main_tournament_id = p_tournament_id)
    ) related
    order by locked_id
  loop
    perform pg_advisory_xact_lock(lock_id);
  end loop;
  select * into tournament_row from public.tournaments where id = p_tournament_id and deleted_at is null for update;
  if not found then raise exception 'Tournament not found' using errcode = 'P0002'; end if;
  expected := public.dpt_admin_tournament_reset_preview(p_tournament_id);
  if expected ->> 'confirmation_token' <> p_confirmation_token then
    raise exception 'Reset preview is stale; obtain a new preview before resetting' using errcode = '40001';
  end if;

  select jsonb_build_object(
    'tournament', to_jsonb(tournament_row),
    'entries', coalesce((select jsonb_agg(to_jsonb(e) order by e.id) from public.tournament_entries e where e.tournament_id = p_tournament_id and e.deleted_at is null), '[]'::jsonb),
    'addons', coalesce((select jsonb_agg(to_jsonb(a) order by a.id) from public.tournament_entry_addons a where a.tournament_id = p_tournament_id), '[]'::jsonb),
    'payouts', coalesce((select jsonb_agg(to_jsonb(p) order by p.id) from public.tournament_payouts p where p.tournament_id = p_tournament_id), '[]'::jsonb),
    'updates', coalesce((select jsonb_agg(to_jsonb(u) order by u.id) from public.tournament_updates u where u.tournament_id = p_tournament_id and u.deleted_at is null), '[]'::jsonb),
    'active_advancements', coalesce((select jsonb_agg(to_jsonb(a) order by a.id) from public.flight_advancements a where a.undone_at is null and (a.flight_tournament_id = p_tournament_id or a.main_tournament_id = p_tournament_id)), '[]'::jsonb),
    'provenance', coalesce((select jsonb_agg(to_jsonb(pr) order by pr.main_tournament_id, pr.player_id) from public.flight_main_entry_provenance pr where pr.main_tournament_id = p_tournament_id or exists (select 1 from public.flight_advancements a where a.main_tournament_id = pr.main_tournament_id and a.player_id = pr.player_id and a.flight_tournament_id = p_tournament_id)), '[]'::jsonb),
    'preview', expected
  ) into before_snapshot;

  -- Remove only this reset's active contributions. Recompute from provenance plus
  -- other active flights, so neither a pre-existing main entry nor another flight
  -- is destroyed. For a main reset, originating flight entries are reopened too.
  for link in
    select a.flight_tournament_id, a.main_tournament_id, a.player_id
    from public.flight_advancements a
    where a.undone_at is null and (a.flight_tournament_id = p_tournament_id or a.main_tournament_id = p_tournament_id)
    for update
  loop
    select * into source from public.flight_main_entry_provenance pr
    where pr.main_tournament_id = link.main_tournament_id and pr.player_id = link.player_id for update;
    if not found then raise exception 'Flight advancement provenance is missing' using errcode = 'P0002'; end if;
    update public.flight_advancements set undone_at = now()
    where flight_tournament_id = link.flight_tournament_id and main_tournament_id = link.main_tournament_id and player_id = link.player_id and undone_at is null;
    select count(*)::integer,
      case when coalesce((select chip_carryover from public.tournaments where id = link.main_tournament_id), 'highest'::public.chip_carryover_mode) = 'sum'::public.chip_carryover_mode
        then source.baseline_total_chips + coalesce(sum(chips_advanced), 0)
        else greatest(source.baseline_total_chips, coalesce(max(chips_advanced), 0)) end
    into remaining_count, computed_chips from public.flight_advancements
    where main_tournament_id = link.main_tournament_id and player_id = link.player_id and undone_at is null;
    if remaining_count = 0 and source.created_by_flight then
      delete from public.tournament_entries where id = source.main_entry_id;
    else
      update public.tournament_entries set initial_chips_count = computed_chips, total_chips = computed_chips, updated_at = now() where id = source.main_entry_id;
      if remaining_count = 0 then delete from public.flight_main_entry_provenance where main_tournament_id = link.main_tournament_id and player_id = link.player_id; end if;
    end if;
    update public.tournament_entries set qualified_flight_player = false, eliminated = false, rank = null, updated_at = now()
    where tournament_id = link.flight_tournament_id and player_id = link.player_id and deleted_at is null;
  end loop;

  update public.tournament_entries set rank = null, checked_in = false, checked_in_by = null, score = null, winnings = null,
    eliminated = false, elimination_sequence = null, final_table = false, qualified_flight_player = false, updated_at = now()
  where tournament_id = p_tournament_id and deleted_at is null;
  select code into type_code from public.tournament_types where id = tournament_row.tournament_type_id;
  if type_code = 'flight' then
    update public.tournament_entries set total_chips = initial_chips_count + total_addon_chips, updated_at = now()
    where tournament_id = p_tournament_id and deleted_at is null and total_chips = 0;
  end if;
  update public.tournaments set registration_closed = false, total_payout_players = null,
    total_payout_distribution_amount = null, updated_at = now() where id = p_tournament_id;

  select jsonb_build_object(
    'entries_cleared', (select count(*) from public.tournament_entries where tournament_id = p_tournament_id and deleted_at is null),
    'addons_preserved', (select count(*) from public.tournament_entry_addons where tournament_id = p_tournament_id),
    'payouts_preserved', (select count(*) from public.tournament_payouts where tournament_id = p_tournament_id),
    'updates_preserved', (select count(*) from public.tournament_updates where tournament_id = p_tournament_id and deleted_at is null),
    'active_flight_advancements_unwound', (expected->'counts'->>'active_flight_advancements_unwound')::integer,
    'registration_reopened', true
  ) into after_counts;
  insert into public.dpt_tournament_reset_snapshots (tournament_id, actor_auth_user_id, actor_profile_id, confirmation_token, before_data, after_data)
  values (p_tournament_id, auth.uid(), actor_profile_id, p_confirmation_token, before_snapshot, after_counts);
  insert into public.dpt_admin_audit_log (actor_auth_user_id, actor_profile_id, action, entity_type, entity_id, tournament_id, before_data, after_data)
  values (auth.uid(), actor_profile_id, 'tournament.full_reset', 'tournament', p_tournament_id::text, p_tournament_id,
    jsonb_build_object('snapshot_recorded', true, 'counts', expected->'counts'), after_counts);
  return jsonb_build_object('tournament_id', p_tournament_id, 'reset', true, 'after_counts', after_counts);
end;
$$;

revoke all on function public.dpt_admin_tournament_reset_preview(bigint) from public, anon;
revoke all on function public.dpt_admin_reset_tournament(bigint,text) from public, anon;
grant execute on function public.dpt_admin_tournament_reset_preview(bigint) to authenticated;
grant execute on function public.dpt_admin_reset_tournament(bigint,text) to authenticated;
commit;
